# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dillon/CppWorkspace/gca

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dillon/CppWorkspace/gca

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dillon/CppWorkspace/gca/CMakeFiles /Users/dillon/CppWorkspace/gca/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dillon/CppWorkspace/gca/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stl-parse

# Build rule for target.
stl-parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stl-parse
.PHONY : stl-parse

# fast build rule for target.
stl-parse/fast:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/build
.PHONY : stl-parse/fast

#=============================================================================
# Target rules for targets named all-tests

# Build rule for target.
all-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all-tests
.PHONY : all-tests

# fast build rule for target.
all-tests/fast:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/build
.PHONY : all-tests/fast

examples/stl_parse.o: examples/stl_parse.cpp.o

.PHONY : examples/stl_parse.o

# target to build an object file
examples/stl_parse.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/examples/stl_parse.cpp.o
.PHONY : examples/stl_parse.cpp.o

examples/stl_parse.i: examples/stl_parse.cpp.i

.PHONY : examples/stl_parse.i

# target to preprocess a source file
examples/stl_parse.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/examples/stl_parse.cpp.i
.PHONY : examples/stl_parse.cpp.i

examples/stl_parse.s: examples/stl_parse.cpp.s

.PHONY : examples/stl_parse.s

# target to generate assembly for a file
examples/stl_parse.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/examples/stl_parse.cpp.s
.PHONY : examples/stl_parse.cpp.s

src/analysis/extract_cuts.o: src/analysis/extract_cuts.cpp.o

.PHONY : src/analysis/extract_cuts.o

# target to build an object file
src/analysis/extract_cuts.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/extract_cuts.cpp.o
.PHONY : src/analysis/extract_cuts.cpp.o

src/analysis/extract_cuts.i: src/analysis/extract_cuts.cpp.i

.PHONY : src/analysis/extract_cuts.i

# target to preprocess a source file
src/analysis/extract_cuts.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/extract_cuts.cpp.i
.PHONY : src/analysis/extract_cuts.cpp.i

src/analysis/extract_cuts.s: src/analysis/extract_cuts.cpp.s

.PHONY : src/analysis/extract_cuts.s

# target to generate assembly for a file
src/analysis/extract_cuts.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/extract_cuts.cpp.s
.PHONY : src/analysis/extract_cuts.cpp.s

src/analysis/gcode_to_cuts.o: src/analysis/gcode_to_cuts.cpp.o

.PHONY : src/analysis/gcode_to_cuts.o

# target to build an object file
src/analysis/gcode_to_cuts.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/gcode_to_cuts.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/gcode_to_cuts.cpp.o
.PHONY : src/analysis/gcode_to_cuts.cpp.o

src/analysis/gcode_to_cuts.i: src/analysis/gcode_to_cuts.cpp.i

.PHONY : src/analysis/gcode_to_cuts.i

# target to preprocess a source file
src/analysis/gcode_to_cuts.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/gcode_to_cuts.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/gcode_to_cuts.cpp.i
.PHONY : src/analysis/gcode_to_cuts.cpp.i

src/analysis/gcode_to_cuts.s: src/analysis/gcode_to_cuts.cpp.s

.PHONY : src/analysis/gcode_to_cuts.s

# target to generate assembly for a file
src/analysis/gcode_to_cuts.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/gcode_to_cuts.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/gcode_to_cuts.cpp.s
.PHONY : src/analysis/gcode_to_cuts.cpp.s

src/analysis/machine_state.o: src/analysis/machine_state.cpp.o

.PHONY : src/analysis/machine_state.o

# target to build an object file
src/analysis/machine_state.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/machine_state.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/machine_state.cpp.o
.PHONY : src/analysis/machine_state.cpp.o

src/analysis/machine_state.i: src/analysis/machine_state.cpp.i

.PHONY : src/analysis/machine_state.i

# target to preprocess a source file
src/analysis/machine_state.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/machine_state.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/machine_state.cpp.i
.PHONY : src/analysis/machine_state.cpp.i

src/analysis/machine_state.s: src/analysis/machine_state.cpp.s

.PHONY : src/analysis/machine_state.s

# target to generate assembly for a file
src/analysis/machine_state.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/machine_state.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/machine_state.cpp.s
.PHONY : src/analysis/machine_state.cpp.s

src/analysis/position_table.o: src/analysis/position_table.cpp.o

.PHONY : src/analysis/position_table.o

# target to build an object file
src/analysis/position_table.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/position_table.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/position_table.cpp.o
.PHONY : src/analysis/position_table.cpp.o

src/analysis/position_table.i: src/analysis/position_table.cpp.i

.PHONY : src/analysis/position_table.i

# target to preprocess a source file
src/analysis/position_table.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/position_table.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/position_table.cpp.i
.PHONY : src/analysis/position_table.cpp.i

src/analysis/position_table.s: src/analysis/position_table.cpp.s

.PHONY : src/analysis/position_table.s

# target to generate assembly for a file
src/analysis/position_table.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/position_table.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/position_table.cpp.s
.PHONY : src/analysis/position_table.cpp.s

src/analysis/profiler.o: src/analysis/profiler.cpp.o

.PHONY : src/analysis/profiler.o

# target to build an object file
src/analysis/profiler.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/profiler.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/profiler.cpp.o
.PHONY : src/analysis/profiler.cpp.o

src/analysis/profiler.i: src/analysis/profiler.cpp.i

.PHONY : src/analysis/profiler.i

# target to preprocess a source file
src/analysis/profiler.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/profiler.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/profiler.cpp.i
.PHONY : src/analysis/profiler.cpp.i

src/analysis/profiler.s: src/analysis/profiler.cpp.s

.PHONY : src/analysis/profiler.s

# target to generate assembly for a file
src/analysis/profiler.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/profiler.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/profiler.cpp.s
.PHONY : src/analysis/profiler.cpp.s

src/analysis/unfold.o: src/analysis/unfold.cpp.o

.PHONY : src/analysis/unfold.o

# target to build an object file
src/analysis/unfold.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/unfold.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/unfold.cpp.o
.PHONY : src/analysis/unfold.cpp.o

src/analysis/unfold.i: src/analysis/unfold.cpp.i

.PHONY : src/analysis/unfold.i

# target to preprocess a source file
src/analysis/unfold.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/unfold.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/unfold.cpp.i
.PHONY : src/analysis/unfold.cpp.i

src/analysis/unfold.s: src/analysis/unfold.cpp.s

.PHONY : src/analysis/unfold.s

# target to generate assembly for a file
src/analysis/unfold.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/unfold.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/unfold.cpp.s
.PHONY : src/analysis/unfold.cpp.s

src/analysis/utils.o: src/analysis/utils.cpp.o

.PHONY : src/analysis/utils.o

# target to build an object file
src/analysis/utils.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/utils.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/utils.cpp.o
.PHONY : src/analysis/utils.cpp.o

src/analysis/utils.i: src/analysis/utils.cpp.i

.PHONY : src/analysis/utils.i

# target to preprocess a source file
src/analysis/utils.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/utils.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/utils.cpp.i
.PHONY : src/analysis/utils.cpp.i

src/analysis/utils.s: src/analysis/utils.cpp.s

.PHONY : src/analysis/utils.s

# target to generate assembly for a file
src/analysis/utils.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/analysis/utils.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/utils.cpp.s
.PHONY : src/analysis/utils.cpp.s

src/checkers/block_rate_checker.o: src/checkers/block_rate_checker.cpp.o

.PHONY : src/checkers/block_rate_checker.o

# target to build an object file
src/checkers/block_rate_checker.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/block_rate_checker.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/block_rate_checker.cpp.o
.PHONY : src/checkers/block_rate_checker.cpp.o

src/checkers/block_rate_checker.i: src/checkers/block_rate_checker.cpp.i

.PHONY : src/checkers/block_rate_checker.i

# target to preprocess a source file
src/checkers/block_rate_checker.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/block_rate_checker.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/block_rate_checker.cpp.i
.PHONY : src/checkers/block_rate_checker.cpp.i

src/checkers/block_rate_checker.s: src/checkers/block_rate_checker.cpp.s

.PHONY : src/checkers/block_rate_checker.s

# target to generate assembly for a file
src/checkers/block_rate_checker.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/block_rate_checker.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/block_rate_checker.cpp.s
.PHONY : src/checkers/block_rate_checker.cpp.s

src/checkers/bounds_checker.o: src/checkers/bounds_checker.cpp.o

.PHONY : src/checkers/bounds_checker.o

# target to build an object file
src/checkers/bounds_checker.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/bounds_checker.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/bounds_checker.cpp.o
.PHONY : src/checkers/bounds_checker.cpp.o

src/checkers/bounds_checker.i: src/checkers/bounds_checker.cpp.i

.PHONY : src/checkers/bounds_checker.i

# target to preprocess a source file
src/checkers/bounds_checker.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/bounds_checker.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/bounds_checker.cpp.i
.PHONY : src/checkers/bounds_checker.cpp.i

src/checkers/bounds_checker.s: src/checkers/bounds_checker.cpp.s

.PHONY : src/checkers/bounds_checker.s

# target to generate assembly for a file
src/checkers/bounds_checker.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/bounds_checker.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/bounds_checker.cpp.s
.PHONY : src/checkers/bounds_checker.cpp.s

src/checkers/forbidden_tool_checker.o: src/checkers/forbidden_tool_checker.cpp.o

.PHONY : src/checkers/forbidden_tool_checker.o

# target to build an object file
src/checkers/forbidden_tool_checker.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/forbidden_tool_checker.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/forbidden_tool_checker.cpp.o
.PHONY : src/checkers/forbidden_tool_checker.cpp.o

src/checkers/forbidden_tool_checker.i: src/checkers/forbidden_tool_checker.cpp.i

.PHONY : src/checkers/forbidden_tool_checker.i

# target to preprocess a source file
src/checkers/forbidden_tool_checker.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/forbidden_tool_checker.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/forbidden_tool_checker.cpp.i
.PHONY : src/checkers/forbidden_tool_checker.cpp.i

src/checkers/forbidden_tool_checker.s: src/checkers/forbidden_tool_checker.cpp.s

.PHONY : src/checkers/forbidden_tool_checker.s

# target to generate assembly for a file
src/checkers/forbidden_tool_checker.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/forbidden_tool_checker.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/forbidden_tool_checker.cpp.s
.PHONY : src/checkers/forbidden_tool_checker.cpp.s

src/checkers/unsafe_spindle_checker.o: src/checkers/unsafe_spindle_checker.cpp.o

.PHONY : src/checkers/unsafe_spindle_checker.o

# target to build an object file
src/checkers/unsafe_spindle_checker.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/unsafe_spindle_checker.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/unsafe_spindle_checker.cpp.o
.PHONY : src/checkers/unsafe_spindle_checker.cpp.o

src/checkers/unsafe_spindle_checker.i: src/checkers/unsafe_spindle_checker.cpp.i

.PHONY : src/checkers/unsafe_spindle_checker.i

# target to preprocess a source file
src/checkers/unsafe_spindle_checker.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/unsafe_spindle_checker.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/unsafe_spindle_checker.cpp.i
.PHONY : src/checkers/unsafe_spindle_checker.cpp.i

src/checkers/unsafe_spindle_checker.s: src/checkers/unsafe_spindle_checker.cpp.s

.PHONY : src/checkers/unsafe_spindle_checker.s

# target to generate assembly for a file
src/checkers/unsafe_spindle_checker.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/checkers/unsafe_spindle_checker.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/checkers/unsafe_spindle_checker.cpp.s
.PHONY : src/checkers/unsafe_spindle_checker.cpp.s

src/core/lexer.o: src/core/lexer.cpp.o

.PHONY : src/core/lexer.o

# target to build an object file
src/core/lexer.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/core/lexer.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/lexer.cpp.o
.PHONY : src/core/lexer.cpp.o

src/core/lexer.i: src/core/lexer.cpp.i

.PHONY : src/core/lexer.i

# target to preprocess a source file
src/core/lexer.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/core/lexer.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/lexer.cpp.i
.PHONY : src/core/lexer.cpp.i

src/core/lexer.s: src/core/lexer.cpp.s

.PHONY : src/core/lexer.s

# target to generate assembly for a file
src/core/lexer.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/core/lexer.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/lexer.cpp.s
.PHONY : src/core/lexer.cpp.s

src/core/parse_stream.o: src/core/parse_stream.cpp.o

.PHONY : src/core/parse_stream.o

# target to build an object file
src/core/parse_stream.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/core/parse_stream.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/parse_stream.cpp.o
.PHONY : src/core/parse_stream.cpp.o

src/core/parse_stream.i: src/core/parse_stream.cpp.i

.PHONY : src/core/parse_stream.i

# target to preprocess a source file
src/core/parse_stream.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/core/parse_stream.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/parse_stream.cpp.i
.PHONY : src/core/parse_stream.cpp.i

src/core/parse_stream.s: src/core/parse_stream.cpp.s

.PHONY : src/core/parse_stream.s

# target to generate assembly for a file
src/core/parse_stream.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/core/parse_stream.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/parse_stream.cpp.s
.PHONY : src/core/parse_stream.cpp.s

src/core/value.o: src/core/value.cpp.o

.PHONY : src/core/value.o

# target to build an object file
src/core/value.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/value.cpp.o
.PHONY : src/core/value.cpp.o

src/core/value.i: src/core/value.cpp.i

.PHONY : src/core/value.i

# target to preprocess a source file
src/core/value.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/value.cpp.i
.PHONY : src/core/value.cpp.i

src/core/value.s: src/core/value.cpp.s

.PHONY : src/core/value.s

# target to generate assembly for a file
src/core/value.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/value.cpp.s
.PHONY : src/core/value.cpp.s

src/dxflib/dl_dxf.o: src/dxflib/dl_dxf.cpp.o

.PHONY : src/dxflib/dl_dxf.o

# target to build an object file
src/dxflib/dl_dxf.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/dxflib/dl_dxf.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/dxflib/dl_dxf.cpp.o
.PHONY : src/dxflib/dl_dxf.cpp.o

src/dxflib/dl_dxf.i: src/dxflib/dl_dxf.cpp.i

.PHONY : src/dxflib/dl_dxf.i

# target to preprocess a source file
src/dxflib/dl_dxf.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/dxflib/dl_dxf.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/dxflib/dl_dxf.cpp.i
.PHONY : src/dxflib/dl_dxf.cpp.i

src/dxflib/dl_dxf.s: src/dxflib/dl_dxf.cpp.s

.PHONY : src/dxflib/dl_dxf.s

# target to generate assembly for a file
src/dxflib/dl_dxf.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/dxflib/dl_dxf.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/dxflib/dl_dxf.cpp.s
.PHONY : src/dxflib/dl_dxf.cpp.s

src/dxflib/dl_writer_ascii.o: src/dxflib/dl_writer_ascii.cpp.o

.PHONY : src/dxflib/dl_writer_ascii.o

# target to build an object file
src/dxflib/dl_writer_ascii.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/dxflib/dl_writer_ascii.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/dxflib/dl_writer_ascii.cpp.o
.PHONY : src/dxflib/dl_writer_ascii.cpp.o

src/dxflib/dl_writer_ascii.i: src/dxflib/dl_writer_ascii.cpp.i

.PHONY : src/dxflib/dl_writer_ascii.i

# target to preprocess a source file
src/dxflib/dl_writer_ascii.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/dxflib/dl_writer_ascii.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/dxflib/dl_writer_ascii.cpp.i
.PHONY : src/dxflib/dl_writer_ascii.cpp.i

src/dxflib/dl_writer_ascii.s: src/dxflib/dl_writer_ascii.cpp.s

.PHONY : src/dxflib/dl_writer_ascii.s

# target to generate assembly for a file
src/dxflib/dl_writer_ascii.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/dxflib/dl_writer_ascii.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/dxflib/dl_writer_ascii.cpp.s
.PHONY : src/dxflib/dl_writer_ascii.cpp.s

src/geometry/arc.o: src/geometry/arc.cpp.o

.PHONY : src/geometry/arc.o

# target to build an object file
src/geometry/arc.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/arc.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/arc.cpp.o
.PHONY : src/geometry/arc.cpp.o

src/geometry/arc.i: src/geometry/arc.cpp.i

.PHONY : src/geometry/arc.i

# target to preprocess a source file
src/geometry/arc.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/arc.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/arc.cpp.i
.PHONY : src/geometry/arc.cpp.i

src/geometry/arc.s: src/geometry/arc.cpp.s

.PHONY : src/geometry/arc.s

# target to generate assembly for a file
src/geometry/arc.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/arc.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/arc.cpp.s
.PHONY : src/geometry/arc.cpp.s

src/geometry/box.o: src/geometry/box.cpp.o

.PHONY : src/geometry/box.o

# target to build an object file
src/geometry/box.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/box.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/box.cpp.o
.PHONY : src/geometry/box.cpp.o

src/geometry/box.i: src/geometry/box.cpp.i

.PHONY : src/geometry/box.i

# target to preprocess a source file
src/geometry/box.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/box.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/box.cpp.i
.PHONY : src/geometry/box.cpp.i

src/geometry/box.s: src/geometry/box.cpp.s

.PHONY : src/geometry/box.s

# target to generate assembly for a file
src/geometry/box.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/box.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/box.cpp.s
.PHONY : src/geometry/box.cpp.s

src/geometry/line.o: src/geometry/line.cpp.o

.PHONY : src/geometry/line.o

# target to build an object file
src/geometry/line.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/line.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/line.cpp.o
.PHONY : src/geometry/line.cpp.o

src/geometry/line.i: src/geometry/line.cpp.i

.PHONY : src/geometry/line.i

# target to preprocess a source file
src/geometry/line.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/line.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/line.cpp.i
.PHONY : src/geometry/line.cpp.i

src/geometry/line.s: src/geometry/line.cpp.s

.PHONY : src/geometry/line.s

# target to generate assembly for a file
src/geometry/line.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/line.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/line.cpp.s
.PHONY : src/geometry/line.cpp.s

src/geometry/point.o: src/geometry/point.cpp.o

.PHONY : src/geometry/point.o

# target to build an object file
src/geometry/point.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/point.cpp.o
.PHONY : src/geometry/point.cpp.o

src/geometry/point.i: src/geometry/point.cpp.i

.PHONY : src/geometry/point.i

# target to preprocess a source file
src/geometry/point.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/point.cpp.i
.PHONY : src/geometry/point.cpp.i

src/geometry/point.s: src/geometry/point.cpp.s

.PHONY : src/geometry/point.s

# target to generate assembly for a file
src/geometry/point.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/point.cpp.s
.PHONY : src/geometry/point.cpp.s

src/geometry/polygon.o: src/geometry/polygon.cpp.o

.PHONY : src/geometry/polygon.o

# target to build an object file
src/geometry/polygon.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/polygon.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/polygon.cpp.o
.PHONY : src/geometry/polygon.cpp.o

src/geometry/polygon.i: src/geometry/polygon.cpp.i

.PHONY : src/geometry/polygon.i

# target to preprocess a source file
src/geometry/polygon.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/polygon.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/polygon.cpp.i
.PHONY : src/geometry/polygon.cpp.i

src/geometry/polygon.s: src/geometry/polygon.cpp.s

.PHONY : src/geometry/polygon.s

# target to generate assembly for a file
src/geometry/polygon.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/polygon.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/polygon.cpp.s
.PHONY : src/geometry/polygon.cpp.s

src/geometry/polyline.o: src/geometry/polyline.cpp.o

.PHONY : src/geometry/polyline.o

# target to build an object file
src/geometry/polyline.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/polyline.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/polyline.cpp.o
.PHONY : src/geometry/polyline.cpp.o

src/geometry/polyline.i: src/geometry/polyline.cpp.i

.PHONY : src/geometry/polyline.i

# target to preprocess a source file
src/geometry/polyline.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/polyline.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/polyline.cpp.i
.PHONY : src/geometry/polyline.cpp.i

src/geometry/polyline.s: src/geometry/polyline.cpp.s

.PHONY : src/geometry/polyline.s

# target to generate assembly for a file
src/geometry/polyline.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/polyline.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/polyline.cpp.s
.PHONY : src/geometry/polyline.cpp.s

src/geometry/triangle.o: src/geometry/triangle.cpp.o

.PHONY : src/geometry/triangle.o

# target to build an object file
src/geometry/triangle.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/triangle.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/triangle.cpp.o
.PHONY : src/geometry/triangle.cpp.o

src/geometry/triangle.i: src/geometry/triangle.cpp.i

.PHONY : src/geometry/triangle.i

# target to preprocess a source file
src/geometry/triangle.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/triangle.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/triangle.cpp.i
.PHONY : src/geometry/triangle.cpp.i

src/geometry/triangle.s: src/geometry/triangle.cpp.s

.PHONY : src/geometry/triangle.s

# target to generate assembly for a file
src/geometry/triangle.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/geometry/triangle.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/triangle.cpp.s
.PHONY : src/geometry/triangle.cpp.s

src/simulators/mill_tool.o: src/simulators/mill_tool.cpp.o

.PHONY : src/simulators/mill_tool.o

# target to build an object file
src/simulators/mill_tool.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/mill_tool.cpp.o
.PHONY : src/simulators/mill_tool.cpp.o

src/simulators/mill_tool.i: src/simulators/mill_tool.cpp.i

.PHONY : src/simulators/mill_tool.i

# target to preprocess a source file
src/simulators/mill_tool.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/mill_tool.cpp.i
.PHONY : src/simulators/mill_tool.cpp.i

src/simulators/mill_tool.s: src/simulators/mill_tool.cpp.s

.PHONY : src/simulators/mill_tool.s

# target to generate assembly for a file
src/simulators/mill_tool.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/mill_tool.cpp.s
.PHONY : src/simulators/mill_tool.cpp.s

src/simulators/sim_mill.o: src/simulators/sim_mill.cpp.o

.PHONY : src/simulators/sim_mill.o

# target to build an object file
src/simulators/sim_mill.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/sim_mill.cpp.o
.PHONY : src/simulators/sim_mill.cpp.o

src/simulators/sim_mill.i: src/simulators/sim_mill.cpp.i

.PHONY : src/simulators/sim_mill.i

# target to preprocess a source file
src/simulators/sim_mill.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/sim_mill.cpp.i
.PHONY : src/simulators/sim_mill.cpp.i

src/simulators/sim_mill.s: src/simulators/sim_mill.cpp.s

.PHONY : src/simulators/sim_mill.s

# target to generate assembly for a file
src/simulators/sim_mill.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/sim_mill.cpp.s
.PHONY : src/simulators/sim_mill.cpp.s

src/synthesis/align_blade.o: src/synthesis/align_blade.cpp.o

.PHONY : src/synthesis/align_blade.o

# target to build an object file
src/synthesis/align_blade.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/align_blade.cpp.o
.PHONY : src/synthesis/align_blade.cpp.o

src/synthesis/align_blade.i: src/synthesis/align_blade.cpp.i

.PHONY : src/synthesis/align_blade.i

# target to preprocess a source file
src/synthesis/align_blade.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/align_blade.cpp.i
.PHONY : src/synthesis/align_blade.cpp.i

src/synthesis/align_blade.s: src/synthesis/align_blade.cpp.s

.PHONY : src/synthesis/align_blade.s

# target to generate assembly for a file
src/synthesis/align_blade.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/align_blade.cpp.s
.PHONY : src/synthesis/align_blade.cpp.s

src/synthesis/axis_3.o: src/synthesis/axis_3.cpp.o

.PHONY : src/synthesis/axis_3.o

# target to build an object file
src/synthesis/axis_3.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/axis_3.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/axis_3.cpp.o
.PHONY : src/synthesis/axis_3.cpp.o

src/synthesis/axis_3.i: src/synthesis/axis_3.cpp.i

.PHONY : src/synthesis/axis_3.i

# target to preprocess a source file
src/synthesis/axis_3.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/axis_3.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/axis_3.cpp.i
.PHONY : src/synthesis/axis_3.cpp.i

src/synthesis/axis_3.s: src/synthesis/axis_3.cpp.s

.PHONY : src/synthesis/axis_3.s

# target to generate assembly for a file
src/synthesis/axis_3.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/axis_3.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/axis_3.cpp.s
.PHONY : src/synthesis/axis_3.cpp.s

src/synthesis/cut.o: src/synthesis/cut.cpp.o

.PHONY : src/synthesis/cut.o

# target to build an object file
src/synthesis/cut.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/cut.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/cut.cpp.o
.PHONY : src/synthesis/cut.cpp.o

src/synthesis/cut.i: src/synthesis/cut.cpp.i

.PHONY : src/synthesis/cut.i

# target to preprocess a source file
src/synthesis/cut.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/cut.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/cut.cpp.i
.PHONY : src/synthesis/cut.cpp.i

src/synthesis/cut.s: src/synthesis/cut.cpp.s

.PHONY : src/synthesis/cut.s

# target to generate assembly for a file
src/synthesis/cut.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/cut.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/cut.cpp.s
.PHONY : src/synthesis/cut.cpp.s

src/synthesis/cut_to_gcode.o: src/synthesis/cut_to_gcode.cpp.o

.PHONY : src/synthesis/cut_to_gcode.o

# target to build an object file
src/synthesis/cut_to_gcode.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/cut_to_gcode.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/cut_to_gcode.cpp.o
.PHONY : src/synthesis/cut_to_gcode.cpp.o

src/synthesis/cut_to_gcode.i: src/synthesis/cut_to_gcode.cpp.i

.PHONY : src/synthesis/cut_to_gcode.i

# target to preprocess a source file
src/synthesis/cut_to_gcode.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/cut_to_gcode.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/cut_to_gcode.cpp.i
.PHONY : src/synthesis/cut_to_gcode.cpp.i

src/synthesis/cut_to_gcode.s: src/synthesis/cut_to_gcode.cpp.s

.PHONY : src/synthesis/cut_to_gcode.s

# target to generate assembly for a file
src/synthesis/cut_to_gcode.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/cut_to_gcode.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/cut_to_gcode.cpp.s
.PHONY : src/synthesis/cut_to_gcode.cpp.s

src/synthesis/dxf_reader.o: src/synthesis/dxf_reader.cpp.o

.PHONY : src/synthesis/dxf_reader.o

# target to build an object file
src/synthesis/dxf_reader.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/dxf_reader.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/dxf_reader.cpp.o
.PHONY : src/synthesis/dxf_reader.cpp.o

src/synthesis/dxf_reader.i: src/synthesis/dxf_reader.cpp.i

.PHONY : src/synthesis/dxf_reader.i

# target to preprocess a source file
src/synthesis/dxf_reader.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/dxf_reader.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/dxf_reader.cpp.i
.PHONY : src/synthesis/dxf_reader.cpp.i

src/synthesis/dxf_reader.s: src/synthesis/dxf_reader.cpp.s

.PHONY : src/synthesis/dxf_reader.s

# target to generate assembly for a file
src/synthesis/dxf_reader.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/dxf_reader.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/dxf_reader.cpp.s
.PHONY : src/synthesis/dxf_reader.cpp.s

src/synthesis/linear_cut.o: src/synthesis/linear_cut.cpp.o

.PHONY : src/synthesis/linear_cut.o

# target to build an object file
src/synthesis/linear_cut.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/linear_cut.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/linear_cut.cpp.o
.PHONY : src/synthesis/linear_cut.cpp.o

src/synthesis/linear_cut.i: src/synthesis/linear_cut.cpp.i

.PHONY : src/synthesis/linear_cut.i

# target to preprocess a source file
src/synthesis/linear_cut.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/linear_cut.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/linear_cut.cpp.i
.PHONY : src/synthesis/linear_cut.cpp.i

src/synthesis/linear_cut.s: src/synthesis/linear_cut.cpp.s

.PHONY : src/synthesis/linear_cut.s

# target to generate assembly for a file
src/synthesis/linear_cut.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/linear_cut.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/linear_cut.cpp.s
.PHONY : src/synthesis/linear_cut.cpp.s

src/synthesis/machine.o: src/synthesis/machine.cpp.o

.PHONY : src/synthesis/machine.o

# target to build an object file
src/synthesis/machine.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/machine.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/machine.cpp.o
.PHONY : src/synthesis/machine.cpp.o

src/synthesis/machine.i: src/synthesis/machine.cpp.i

.PHONY : src/synthesis/machine.i

# target to preprocess a source file
src/synthesis/machine.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/machine.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/machine.cpp.i
.PHONY : src/synthesis/machine.cpp.i

src/synthesis/machine.s: src/synthesis/machine.cpp.s

.PHONY : src/synthesis/machine.s

# target to generate assembly for a file
src/synthesis/machine.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/machine.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/machine.cpp.s
.PHONY : src/synthesis/machine.cpp.s

src/synthesis/output.o: src/synthesis/output.cpp.o

.PHONY : src/synthesis/output.o

# target to build an object file
src/synthesis/output.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/output.cpp.o
.PHONY : src/synthesis/output.cpp.o

src/synthesis/output.i: src/synthesis/output.cpp.i

.PHONY : src/synthesis/output.i

# target to preprocess a source file
src/synthesis/output.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/output.cpp.i
.PHONY : src/synthesis/output.cpp.i

src/synthesis/output.s: src/synthesis/output.cpp.s

.PHONY : src/synthesis/output.s

# target to generate assembly for a file
src/synthesis/output.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/output.cpp.s
.PHONY : src/synthesis/output.cpp.s

src/synthesis/schedule_cuts.o: src/synthesis/schedule_cuts.cpp.o

.PHONY : src/synthesis/schedule_cuts.o

# target to build an object file
src/synthesis/schedule_cuts.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/schedule_cuts.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/schedule_cuts.cpp.o
.PHONY : src/synthesis/schedule_cuts.cpp.o

src/synthesis/schedule_cuts.i: src/synthesis/schedule_cuts.cpp.i

.PHONY : src/synthesis/schedule_cuts.i

# target to preprocess a source file
src/synthesis/schedule_cuts.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/schedule_cuts.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/schedule_cuts.cpp.i
.PHONY : src/synthesis/schedule_cuts.cpp.i

src/synthesis/schedule_cuts.s: src/synthesis/schedule_cuts.cpp.s

.PHONY : src/synthesis/schedule_cuts.s

# target to generate assembly for a file
src/synthesis/schedule_cuts.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/schedule_cuts.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/schedule_cuts.cpp.s
.PHONY : src/synthesis/schedule_cuts.cpp.s

src/synthesis/shapes_to_gcode.o: src/synthesis/shapes_to_gcode.cpp.o

.PHONY : src/synthesis/shapes_to_gcode.o

# target to build an object file
src/synthesis/shapes_to_gcode.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/shapes_to_gcode.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/shapes_to_gcode.cpp.o
.PHONY : src/synthesis/shapes_to_gcode.cpp.o

src/synthesis/shapes_to_gcode.i: src/synthesis/shapes_to_gcode.cpp.i

.PHONY : src/synthesis/shapes_to_gcode.i

# target to preprocess a source file
src/synthesis/shapes_to_gcode.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/shapes_to_gcode.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/shapes_to_gcode.cpp.i
.PHONY : src/synthesis/shapes_to_gcode.cpp.i

src/synthesis/shapes_to_gcode.s: src/synthesis/shapes_to_gcode.cpp.s

.PHONY : src/synthesis/shapes_to_gcode.s

# target to generate assembly for a file
src/synthesis/shapes_to_gcode.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/shapes_to_gcode.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/shapes_to_gcode.cpp.s
.PHONY : src/synthesis/shapes_to_gcode.cpp.s

src/synthesis/shapes_to_toolpaths.o: src/synthesis/shapes_to_toolpaths.cpp.o

.PHONY : src/synthesis/shapes_to_toolpaths.o

# target to build an object file
src/synthesis/shapes_to_toolpaths.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/shapes_to_toolpaths.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/shapes_to_toolpaths.cpp.o
.PHONY : src/synthesis/shapes_to_toolpaths.cpp.o

src/synthesis/shapes_to_toolpaths.i: src/synthesis/shapes_to_toolpaths.cpp.i

.PHONY : src/synthesis/shapes_to_toolpaths.i

# target to preprocess a source file
src/synthesis/shapes_to_toolpaths.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/shapes_to_toolpaths.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/shapes_to_toolpaths.cpp.i
.PHONY : src/synthesis/shapes_to_toolpaths.cpp.i

src/synthesis/shapes_to_toolpaths.s: src/synthesis/shapes_to_toolpaths.cpp.s

.PHONY : src/synthesis/shapes_to_toolpaths.s

# target to generate assembly for a file
src/synthesis/shapes_to_toolpaths.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/shapes_to_toolpaths.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/shapes_to_toolpaths.cpp.s
.PHONY : src/synthesis/shapes_to_toolpaths.cpp.s

src/synthesis/spline_sampling.o: src/synthesis/spline_sampling.cpp.o

.PHONY : src/synthesis/spline_sampling.o

# target to build an object file
src/synthesis/spline_sampling.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/spline_sampling.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/spline_sampling.cpp.o
.PHONY : src/synthesis/spline_sampling.cpp.o

src/synthesis/spline_sampling.i: src/synthesis/spline_sampling.cpp.i

.PHONY : src/synthesis/spline_sampling.i

# target to preprocess a source file
src/synthesis/spline_sampling.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/spline_sampling.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/spline_sampling.cpp.i
.PHONY : src/synthesis/spline_sampling.cpp.i

src/synthesis/spline_sampling.s: src/synthesis/spline_sampling.cpp.s

.PHONY : src/synthesis/spline_sampling.s

# target to generate assembly for a file
src/synthesis/spline_sampling.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/spline_sampling.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/spline_sampling.cpp.s
.PHONY : src/synthesis/spline_sampling.cpp.s

src/synthesis/toolpath.o: src/synthesis/toolpath.cpp.o

.PHONY : src/synthesis/toolpath.o

# target to build an object file
src/synthesis/toolpath.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/toolpath.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/toolpath.cpp.o
.PHONY : src/synthesis/toolpath.cpp.o

src/synthesis/toolpath.i: src/synthesis/toolpath.cpp.i

.PHONY : src/synthesis/toolpath.i

# target to preprocess a source file
src/synthesis/toolpath.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/toolpath.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/toolpath.cpp.i
.PHONY : src/synthesis/toolpath.cpp.i

src/synthesis/toolpath.s: src/synthesis/toolpath.cpp.s

.PHONY : src/synthesis/toolpath.s

# target to generate assembly for a file
src/synthesis/toolpath.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/toolpath.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/toolpath.cpp.s
.PHONY : src/synthesis/toolpath.cpp.s

src/synthesis/toolpath_generation.o: src/synthesis/toolpath_generation.cpp.o

.PHONY : src/synthesis/toolpath_generation.o

# target to build an object file
src/synthesis/toolpath_generation.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/toolpath_generation.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/toolpath_generation.cpp.o
.PHONY : src/synthesis/toolpath_generation.cpp.o

src/synthesis/toolpath_generation.i: src/synthesis/toolpath_generation.cpp.i

.PHONY : src/synthesis/toolpath_generation.i

# target to preprocess a source file
src/synthesis/toolpath_generation.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/toolpath_generation.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/toolpath_generation.cpp.i
.PHONY : src/synthesis/toolpath_generation.cpp.i

src/synthesis/toolpath_generation.s: src/synthesis/toolpath_generation.cpp.s

.PHONY : src/synthesis/toolpath_generation.s

# target to generate assembly for a file
src/synthesis/toolpath_generation.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/synthesis/toolpath_generation.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/toolpath_generation.cpp.s
.PHONY : src/synthesis/toolpath_generation.cpp.s

src/system/arena_allocator.o: src/system/arena_allocator.cpp.o

.PHONY : src/system/arena_allocator.o

# target to build an object file
src/system/arena_allocator.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/arena_allocator.cpp.o
.PHONY : src/system/arena_allocator.cpp.o

src/system/arena_allocator.i: src/system/arena_allocator.cpp.i

.PHONY : src/system/arena_allocator.i

# target to preprocess a source file
src/system/arena_allocator.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/arena_allocator.cpp.i
.PHONY : src/system/arena_allocator.cpp.i

src/system/arena_allocator.s: src/system/arena_allocator.cpp.s

.PHONY : src/system/arena_allocator.s

# target to generate assembly for a file
src/system/arena_allocator.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/arena_allocator.cpp.s
.PHONY : src/system/arena_allocator.cpp.s

src/system/file.o: src/system/file.cpp.o

.PHONY : src/system/file.o

# target to build an object file
src/system/file.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/file.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/file.cpp.o
.PHONY : src/system/file.cpp.o

src/system/file.i: src/system/file.cpp.i

.PHONY : src/system/file.i

# target to preprocess a source file
src/system/file.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/file.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/file.cpp.i
.PHONY : src/system/file.cpp.i

src/system/file.s: src/system/file.cpp.s

.PHONY : src/system/file.s

# target to generate assembly for a file
src/system/file.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/file.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/file.cpp.s
.PHONY : src/system/file.cpp.s

src/system/parse_stl.o: src/system/parse_stl.cpp.o

.PHONY : src/system/parse_stl.o

# target to build an object file
src/system/parse_stl.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/parse_stl.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/parse_stl.cpp.o
.PHONY : src/system/parse_stl.cpp.o

src/system/parse_stl.i: src/system/parse_stl.cpp.i

.PHONY : src/system/parse_stl.i

# target to preprocess a source file
src/system/parse_stl.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/parse_stl.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/parse_stl.cpp.i
.PHONY : src/system/parse_stl.cpp.i

src/system/parse_stl.s: src/system/parse_stl.cpp.s

.PHONY : src/system/parse_stl.s

# target to generate assembly for a file
src/system/parse_stl.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/parse_stl.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/parse_stl.cpp.s
.PHONY : src/system/parse_stl.cpp.s

src/system/settings.o: src/system/settings.cpp.o

.PHONY : src/system/settings.o

# target to build an object file
src/system/settings.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/settings.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/settings.cpp.o
.PHONY : src/system/settings.cpp.o

src/system/settings.i: src/system/settings.cpp.i

.PHONY : src/system/settings.i

# target to preprocess a source file
src/system/settings.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/settings.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/settings.cpp.i
.PHONY : src/system/settings.cpp.i

src/system/settings.s: src/system/settings.cpp.s

.PHONY : src/system/settings.s

# target to generate assembly for a file
src/system/settings.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/system/settings.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/settings.cpp.s
.PHONY : src/system/settings.cpp.s

src/transformers/feed_changer.o: src/transformers/feed_changer.cpp.o

.PHONY : src/transformers/feed_changer.o

# target to build an object file
src/transformers/feed_changer.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/transformers/feed_changer.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/transformers/feed_changer.cpp.o
.PHONY : src/transformers/feed_changer.cpp.o

src/transformers/feed_changer.i: src/transformers/feed_changer.cpp.i

.PHONY : src/transformers/feed_changer.i

# target to preprocess a source file
src/transformers/feed_changer.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/transformers/feed_changer.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/transformers/feed_changer.cpp.i
.PHONY : src/transformers/feed_changer.cpp.i

src/transformers/feed_changer.s: src/transformers/feed_changer.cpp.s

.PHONY : src/transformers/feed_changer.s

# target to generate assembly for a file
src/transformers/feed_changer.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/transformers/feed_changer.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/transformers/feed_changer.cpp.s
.PHONY : src/transformers/feed_changer.cpp.s

src/transformers/retarget.o: src/transformers/retarget.cpp.o

.PHONY : src/transformers/retarget.o

# target to build an object file
src/transformers/retarget.cpp.o:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/transformers/retarget.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/transformers/retarget.cpp.o
.PHONY : src/transformers/retarget.cpp.o

src/transformers/retarget.i: src/transformers/retarget.cpp.i

.PHONY : src/transformers/retarget.i

# target to preprocess a source file
src/transformers/retarget.cpp.i:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/transformers/retarget.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/transformers/retarget.cpp.i
.PHONY : src/transformers/retarget.cpp.i

src/transformers/retarget.s: src/transformers/retarget.cpp.s

.PHONY : src/transformers/retarget.s

# target to generate assembly for a file
src/transformers/retarget.cpp.s:
	$(MAKE) -f CMakeFiles/stl-parse.dir/build.make CMakeFiles/stl-parse.dir/src/transformers/retarget.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/transformers/retarget.cpp.s
.PHONY : src/transformers/retarget.cpp.s

test/analysis_tests.o: test/analysis_tests.cpp.o

.PHONY : test/analysis_tests.o

# target to build an object file
test/analysis_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/analysis_tests.cpp.o
.PHONY : test/analysis_tests.cpp.o

test/analysis_tests.i: test/analysis_tests.cpp.i

.PHONY : test/analysis_tests.i

# target to preprocess a source file
test/analysis_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/analysis_tests.cpp.i
.PHONY : test/analysis_tests.cpp.i

test/analysis_tests.s: test/analysis_tests.cpp.s

.PHONY : test/analysis_tests.s

# target to generate assembly for a file
test/analysis_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/analysis_tests.cpp.s
.PHONY : test/analysis_tests.cpp.s

test/arc_tests.o: test/arc_tests.cpp.o

.PHONY : test/arc_tests.o

# target to build an object file
test/arc_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/arc_tests.cpp.o
.PHONY : test/arc_tests.cpp.o

test/arc_tests.i: test/arc_tests.cpp.i

.PHONY : test/arc_tests.i

# target to preprocess a source file
test/arc_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/arc_tests.cpp.i
.PHONY : test/arc_tests.cpp.i

test/arc_tests.s: test/arc_tests.cpp.s

.PHONY : test/arc_tests.s

# target to generate assembly for a file
test/arc_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/arc_tests.cpp.s
.PHONY : test/arc_tests.cpp.s

test/axis_3_tests.o: test/axis_3_tests.cpp.o

.PHONY : test/axis_3_tests.o

# target to build an object file
test/axis_3_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/axis_3_tests.cpp.o
.PHONY : test/axis_3_tests.cpp.o

test/axis_3_tests.i: test/axis_3_tests.cpp.i

.PHONY : test/axis_3_tests.i

# target to preprocess a source file
test/axis_3_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/axis_3_tests.cpp.i
.PHONY : test/axis_3_tests.cpp.i

test/axis_3_tests.s: test/axis_3_tests.cpp.s

.PHONY : test/axis_3_tests.s

# target to generate assembly for a file
test/axis_3_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/axis_3_tests.cpp.s
.PHONY : test/axis_3_tests.cpp.s

test/checker_tests.o: test/checker_tests.cpp.o

.PHONY : test/checker_tests.o

# target to build an object file
test/checker_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/checker_tests.cpp.o
.PHONY : test/checker_tests.cpp.o

test/checker_tests.i: test/checker_tests.cpp.i

.PHONY : test/checker_tests.i

# target to preprocess a source file
test/checker_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/checker_tests.cpp.i
.PHONY : test/checker_tests.cpp.i

test/checker_tests.s: test/checker_tests.cpp.s

.PHONY : test/checker_tests.s

# target to generate assembly for a file
test/checker_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/checker_tests.cpp.s
.PHONY : test/checker_tests.cpp.s

test/circular_arc_tests.o: test/circular_arc_tests.cpp.o

.PHONY : test/circular_arc_tests.o

# target to build an object file
test/circular_arc_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/circular_arc_tests.cpp.o
.PHONY : test/circular_arc_tests.cpp.o

test/circular_arc_tests.i: test/circular_arc_tests.cpp.i

.PHONY : test/circular_arc_tests.i

# target to preprocess a source file
test/circular_arc_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/circular_arc_tests.cpp.i
.PHONY : test/circular_arc_tests.cpp.i

test/circular_arc_tests.s: test/circular_arc_tests.cpp.s

.PHONY : test/circular_arc_tests.s

# target to generate assembly for a file
test/circular_arc_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/circular_arc_tests.cpp.s
.PHONY : test/circular_arc_tests.cpp.s

test/cut_scheduling_tests.o: test/cut_scheduling_tests.cpp.o

.PHONY : test/cut_scheduling_tests.o

# target to build an object file
test/cut_scheduling_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_scheduling_tests.cpp.o
.PHONY : test/cut_scheduling_tests.cpp.o

test/cut_scheduling_tests.i: test/cut_scheduling_tests.cpp.i

.PHONY : test/cut_scheduling_tests.i

# target to preprocess a source file
test/cut_scheduling_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_scheduling_tests.cpp.i
.PHONY : test/cut_scheduling_tests.cpp.i

test/cut_scheduling_tests.s: test/cut_scheduling_tests.cpp.s

.PHONY : test/cut_scheduling_tests.s

# target to generate assembly for a file
test/cut_scheduling_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_scheduling_tests.cpp.s
.PHONY : test/cut_scheduling_tests.cpp.s

test/cut_tests.o: test/cut_tests.cpp.o

.PHONY : test/cut_tests.o

# target to build an object file
test/cut_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_tests.cpp.o
.PHONY : test/cut_tests.cpp.o

test/cut_tests.i: test/cut_tests.cpp.i

.PHONY : test/cut_tests.i

# target to preprocess a source file
test/cut_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_tests.cpp.i
.PHONY : test/cut_tests.cpp.i

test/cut_tests.s: test/cut_tests.cpp.s

.PHONY : test/cut_tests.s

# target to generate assembly for a file
test/cut_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_tests.cpp.s
.PHONY : test/cut_tests.cpp.s

test/dxf_to_gcode_tests.o: test/dxf_to_gcode_tests.cpp.o

.PHONY : test/dxf_to_gcode_tests.o

# target to build an object file
test/dxf_to_gcode_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/dxf_to_gcode_tests.cpp.o
.PHONY : test/dxf_to_gcode_tests.cpp.o

test/dxf_to_gcode_tests.i: test/dxf_to_gcode_tests.cpp.i

.PHONY : test/dxf_to_gcode_tests.i

# target to preprocess a source file
test/dxf_to_gcode_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/dxf_to_gcode_tests.cpp.i
.PHONY : test/dxf_to_gcode_tests.cpp.i

test/dxf_to_gcode_tests.s: test/dxf_to_gcode_tests.cpp.s

.PHONY : test/dxf_to_gcode_tests.s

# target to generate assembly for a file
test/dxf_to_gcode_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/dxf_to_gcode_tests.cpp.s
.PHONY : test/dxf_to_gcode_tests.cpp.s

test/gcode_to_cuts_tests.o: test/gcode_to_cuts_tests.cpp.o

.PHONY : test/gcode_to_cuts_tests.o

# target to build an object file
test/gcode_to_cuts_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/gcode_to_cuts_tests.cpp.o
.PHONY : test/gcode_to_cuts_tests.cpp.o

test/gcode_to_cuts_tests.i: test/gcode_to_cuts_tests.cpp.i

.PHONY : test/gcode_to_cuts_tests.i

# target to preprocess a source file
test/gcode_to_cuts_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/gcode_to_cuts_tests.cpp.i
.PHONY : test/gcode_to_cuts_tests.cpp.i

test/gcode_to_cuts_tests.s: test/gcode_to_cuts_tests.cpp.s

.PHONY : test/gcode_to_cuts_tests.s

# target to generate assembly for a file
test/gcode_to_cuts_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/gcode_to_cuts_tests.cpp.s
.PHONY : test/gcode_to_cuts_tests.cpp.s

test/lexer_tests.o: test/lexer_tests.cpp.o

.PHONY : test/lexer_tests.o

# target to build an object file
test/lexer_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/lexer_tests.cpp.o
.PHONY : test/lexer_tests.cpp.o

test/lexer_tests.i: test/lexer_tests.cpp.i

.PHONY : test/lexer_tests.i

# target to preprocess a source file
test/lexer_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/lexer_tests.cpp.i
.PHONY : test/lexer_tests.cpp.i

test/lexer_tests.s: test/lexer_tests.cpp.s

.PHONY : test/lexer_tests.s

# target to generate assembly for a file
test/lexer_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/lexer_tests.cpp.s
.PHONY : test/lexer_tests.cpp.s

test/line_tests.o: test/line_tests.cpp.o

.PHONY : test/line_tests.o

# target to build an object file
test/line_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/line_tests.cpp.o
.PHONY : test/line_tests.cpp.o

test/line_tests.i: test/line_tests.cpp.i

.PHONY : test/line_tests.i

# target to preprocess a source file
test/line_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/line_tests.cpp.i
.PHONY : test/line_tests.cpp.i

test/line_tests.s: test/line_tests.cpp.s

.PHONY : test/line_tests.s

# target to generate assembly for a file
test/line_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/line_tests.cpp.s
.PHONY : test/line_tests.cpp.s

test/machine_state_tests.o: test/machine_state_tests.cpp.o

.PHONY : test/machine_state_tests.o

# target to build an object file
test/machine_state_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/machine_state_tests.cpp.o
.PHONY : test/machine_state_tests.cpp.o

test/machine_state_tests.i: test/machine_state_tests.cpp.i

.PHONY : test/machine_state_tests.i

# target to preprocess a source file
test/machine_state_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/machine_state_tests.cpp.i
.PHONY : test/machine_state_tests.cpp.i

test/machine_state_tests.s: test/machine_state_tests.cpp.s

.PHONY : test/machine_state_tests.s

# target to generate assembly for a file
test/machine_state_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/machine_state_tests.cpp.s
.PHONY : test/machine_state_tests.cpp.s

test/mill_simulator_tests.o: test/mill_simulator_tests.cpp.o

.PHONY : test/mill_simulator_tests.o

# target to build an object file
test/mill_simulator_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/mill_simulator_tests.cpp.o
.PHONY : test/mill_simulator_tests.cpp.o

test/mill_simulator_tests.i: test/mill_simulator_tests.cpp.i

.PHONY : test/mill_simulator_tests.i

# target to preprocess a source file
test/mill_simulator_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/mill_simulator_tests.cpp.i
.PHONY : test/mill_simulator_tests.cpp.i

test/mill_simulator_tests.s: test/mill_simulator_tests.cpp.s

.PHONY : test/mill_simulator_tests.s

# target to generate assembly for a file
test/mill_simulator_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/mill_simulator_tests.cpp.s
.PHONY : test/mill_simulator_tests.cpp.s

test/point_tests.o: test/point_tests.cpp.o

.PHONY : test/point_tests.o

# target to build an object file
test/point_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/point_tests.cpp.o
.PHONY : test/point_tests.cpp.o

test/point_tests.i: test/point_tests.cpp.i

.PHONY : test/point_tests.i

# target to preprocess a source file
test/point_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/point_tests.cpp.i
.PHONY : test/point_tests.cpp.i

test/point_tests.s: test/point_tests.cpp.s

.PHONY : test/point_tests.s

# target to generate assembly for a file
test/point_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/point_tests.cpp.s
.PHONY : test/point_tests.cpp.s

test/polygon_tests.o: test/polygon_tests.cpp.o

.PHONY : test/polygon_tests.o

# target to build an object file
test/polygon_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/polygon_tests.cpp.o
.PHONY : test/polygon_tests.cpp.o

test/polygon_tests.i: test/polygon_tests.cpp.i

.PHONY : test/polygon_tests.i

# target to preprocess a source file
test/polygon_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/polygon_tests.cpp.i
.PHONY : test/polygon_tests.cpp.i

test/polygon_tests.s: test/polygon_tests.cpp.s

.PHONY : test/polygon_tests.s

# target to generate assembly for a file
test/polygon_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/polygon_tests.cpp.s
.PHONY : test/polygon_tests.cpp.s

test/polyline_tests.o: test/polyline_tests.cpp.o

.PHONY : test/polyline_tests.o

# target to build an object file
test/polyline_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/polyline_tests.cpp.o
.PHONY : test/polyline_tests.cpp.o

test/polyline_tests.i: test/polyline_tests.cpp.i

.PHONY : test/polyline_tests.i

# target to preprocess a source file
test/polyline_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/polyline_tests.cpp.i
.PHONY : test/polyline_tests.cpp.i

test/polyline_tests.s: test/polyline_tests.cpp.s

.PHONY : test/polyline_tests.s

# target to generate assembly for a file
test/polyline_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/polyline_tests.cpp.s
.PHONY : test/polyline_tests.cpp.s

test/position_table_tests.o: test/position_table_tests.cpp.o

.PHONY : test/position_table_tests.o

# target to build an object file
test/position_table_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/position_table_tests.cpp.o
.PHONY : test/position_table_tests.cpp.o

test/position_table_tests.i: test/position_table_tests.cpp.i

.PHONY : test/position_table_tests.i

# target to preprocess a source file
test/position_table_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/position_table_tests.cpp.i
.PHONY : test/position_table_tests.cpp.i

test/position_table_tests.s: test/position_table_tests.cpp.s

.PHONY : test/position_table_tests.s

# target to generate assembly for a file
test/position_table_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/position_table_tests.cpp.s
.PHONY : test/position_table_tests.cpp.s

test/retargeting_tests.o: test/retargeting_tests.cpp.o

.PHONY : test/retargeting_tests.o

# target to build an object file
test/retargeting_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/retargeting_tests.cpp.o
.PHONY : test/retargeting_tests.cpp.o

test/retargeting_tests.i: test/retargeting_tests.cpp.i

.PHONY : test/retargeting_tests.i

# target to preprocess a source file
test/retargeting_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/retargeting_tests.cpp.i
.PHONY : test/retargeting_tests.cpp.i

test/retargeting_tests.s: test/retargeting_tests.cpp.s

.PHONY : test/retargeting_tests.s

# target to generate assembly for a file
test/retargeting_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/retargeting_tests.cpp.s
.PHONY : test/retargeting_tests.cpp.s

test/shapes_to_toolpaths_tests.o: test/shapes_to_toolpaths_tests.cpp.o

.PHONY : test/shapes_to_toolpaths_tests.o

# target to build an object file
test/shapes_to_toolpaths_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/shapes_to_toolpaths_tests.cpp.o
.PHONY : test/shapes_to_toolpaths_tests.cpp.o

test/shapes_to_toolpaths_tests.i: test/shapes_to_toolpaths_tests.cpp.i

.PHONY : test/shapes_to_toolpaths_tests.i

# target to preprocess a source file
test/shapes_to_toolpaths_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/shapes_to_toolpaths_tests.cpp.i
.PHONY : test/shapes_to_toolpaths_tests.cpp.i

test/shapes_to_toolpaths_tests.s: test/shapes_to_toolpaths_tests.cpp.s

.PHONY : test/shapes_to_toolpaths_tests.s

# target to generate assembly for a file
test/shapes_to_toolpaths_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/shapes_to_toolpaths_tests.cpp.s
.PHONY : test/shapes_to_toolpaths_tests.cpp.s

test/spline_tests.o: test/spline_tests.cpp.o

.PHONY : test/spline_tests.o

# target to build an object file
test/spline_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/spline_tests.cpp.o
.PHONY : test/spline_tests.cpp.o

test/spline_tests.i: test/spline_tests.cpp.i

.PHONY : test/spline_tests.i

# target to preprocess a source file
test/spline_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/spline_tests.cpp.i
.PHONY : test/spline_tests.cpp.i

test/spline_tests.s: test/spline_tests.cpp.s

.PHONY : test/spline_tests.s

# target to generate assembly for a file
test/spline_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/spline_tests.cpp.s
.PHONY : test/spline_tests.cpp.s

test/system_algorithm_tests.o: test/system_algorithm_tests.cpp.o

.PHONY : test/system_algorithm_tests.o

# target to build an object file
test/system_algorithm_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/system_algorithm_tests.cpp.o
.PHONY : test/system_algorithm_tests.cpp.o

test/system_algorithm_tests.i: test/system_algorithm_tests.cpp.i

.PHONY : test/system_algorithm_tests.i

# target to preprocess a source file
test/system_algorithm_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/system_algorithm_tests.cpp.i
.PHONY : test/system_algorithm_tests.cpp.i

test/system_algorithm_tests.s: test/system_algorithm_tests.cpp.s

.PHONY : test/system_algorithm_tests.s

# target to generate assembly for a file
test/system_algorithm_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/system_algorithm_tests.cpp.s
.PHONY : test/system_algorithm_tests.cpp.s

test/toolpath_tests.o: test/toolpath_tests.cpp.o

.PHONY : test/toolpath_tests.o

# target to build an object file
test/toolpath_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/toolpath_tests.cpp.o
.PHONY : test/toolpath_tests.cpp.o

test/toolpath_tests.i: test/toolpath_tests.cpp.i

.PHONY : test/toolpath_tests.i

# target to preprocess a source file
test/toolpath_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/toolpath_tests.cpp.i
.PHONY : test/toolpath_tests.cpp.i

test/toolpath_tests.s: test/toolpath_tests.cpp.s

.PHONY : test/toolpath_tests.s

# target to generate assembly for a file
test/toolpath_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/toolpath_tests.cpp.s
.PHONY : test/toolpath_tests.cpp.s

test/transformer_tests.o: test/transformer_tests.cpp.o

.PHONY : test/transformer_tests.o

# target to build an object file
test/transformer_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/transformer_tests.cpp.o
.PHONY : test/transformer_tests.cpp.o

test/transformer_tests.i: test/transformer_tests.cpp.i

.PHONY : test/transformer_tests.i

# target to preprocess a source file
test/transformer_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/transformer_tests.cpp.i
.PHONY : test/transformer_tests.cpp.i

test/transformer_tests.s: test/transformer_tests.cpp.s

.PHONY : test/transformer_tests.s

# target to generate assembly for a file
test/transformer_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/transformer_tests.cpp.s
.PHONY : test/transformer_tests.cpp.s

test/triangle_tests.o: test/triangle_tests.cpp.o

.PHONY : test/triangle_tests.o

# target to build an object file
test/triangle_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/triangle_tests.cpp.o
.PHONY : test/triangle_tests.cpp.o

test/triangle_tests.i: test/triangle_tests.cpp.i

.PHONY : test/triangle_tests.i

# target to preprocess a source file
test/triangle_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/triangle_tests.cpp.i
.PHONY : test/triangle_tests.cpp.i

test/triangle_tests.s: test/triangle_tests.cpp.s

.PHONY : test/triangle_tests.s

# target to generate assembly for a file
test/triangle_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/triangle_tests.cpp.s
.PHONY : test/triangle_tests.cpp.s

test/unfold_tests.o: test/unfold_tests.cpp.o

.PHONY : test/unfold_tests.o

# target to build an object file
test/unfold_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/unfold_tests.cpp.o
.PHONY : test/unfold_tests.cpp.o

test/unfold_tests.i: test/unfold_tests.cpp.i

.PHONY : test/unfold_tests.i

# target to preprocess a source file
test/unfold_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/unfold_tests.cpp.i
.PHONY : test/unfold_tests.cpp.i

test/unfold_tests.s: test/unfold_tests.cpp.s

.PHONY : test/unfold_tests.s

# target to generate assembly for a file
test/unfold_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/unfold_tests.cpp.s
.PHONY : test/unfold_tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stl-parse"
	@echo "... all-tests"
	@echo "... examples/stl_parse.o"
	@echo "... examples/stl_parse.i"
	@echo "... examples/stl_parse.s"
	@echo "... src/analysis/extract_cuts.o"
	@echo "... src/analysis/extract_cuts.i"
	@echo "... src/analysis/extract_cuts.s"
	@echo "... src/analysis/gcode_to_cuts.o"
	@echo "... src/analysis/gcode_to_cuts.i"
	@echo "... src/analysis/gcode_to_cuts.s"
	@echo "... src/analysis/machine_state.o"
	@echo "... src/analysis/machine_state.i"
	@echo "... src/analysis/machine_state.s"
	@echo "... src/analysis/position_table.o"
	@echo "... src/analysis/position_table.i"
	@echo "... src/analysis/position_table.s"
	@echo "... src/analysis/profiler.o"
	@echo "... src/analysis/profiler.i"
	@echo "... src/analysis/profiler.s"
	@echo "... src/analysis/unfold.o"
	@echo "... src/analysis/unfold.i"
	@echo "... src/analysis/unfold.s"
	@echo "... src/analysis/utils.o"
	@echo "... src/analysis/utils.i"
	@echo "... src/analysis/utils.s"
	@echo "... src/checkers/block_rate_checker.o"
	@echo "... src/checkers/block_rate_checker.i"
	@echo "... src/checkers/block_rate_checker.s"
	@echo "... src/checkers/bounds_checker.o"
	@echo "... src/checkers/bounds_checker.i"
	@echo "... src/checkers/bounds_checker.s"
	@echo "... src/checkers/forbidden_tool_checker.o"
	@echo "... src/checkers/forbidden_tool_checker.i"
	@echo "... src/checkers/forbidden_tool_checker.s"
	@echo "... src/checkers/unsafe_spindle_checker.o"
	@echo "... src/checkers/unsafe_spindle_checker.i"
	@echo "... src/checkers/unsafe_spindle_checker.s"
	@echo "... src/core/lexer.o"
	@echo "... src/core/lexer.i"
	@echo "... src/core/lexer.s"
	@echo "... src/core/parse_stream.o"
	@echo "... src/core/parse_stream.i"
	@echo "... src/core/parse_stream.s"
	@echo "... src/core/value.o"
	@echo "... src/core/value.i"
	@echo "... src/core/value.s"
	@echo "... src/dxflib/dl_dxf.o"
	@echo "... src/dxflib/dl_dxf.i"
	@echo "... src/dxflib/dl_dxf.s"
	@echo "... src/dxflib/dl_writer_ascii.o"
	@echo "... src/dxflib/dl_writer_ascii.i"
	@echo "... src/dxflib/dl_writer_ascii.s"
	@echo "... src/geometry/arc.o"
	@echo "... src/geometry/arc.i"
	@echo "... src/geometry/arc.s"
	@echo "... src/geometry/box.o"
	@echo "... src/geometry/box.i"
	@echo "... src/geometry/box.s"
	@echo "... src/geometry/line.o"
	@echo "... src/geometry/line.i"
	@echo "... src/geometry/line.s"
	@echo "... src/geometry/point.o"
	@echo "... src/geometry/point.i"
	@echo "... src/geometry/point.s"
	@echo "... src/geometry/polygon.o"
	@echo "... src/geometry/polygon.i"
	@echo "... src/geometry/polygon.s"
	@echo "... src/geometry/polyline.o"
	@echo "... src/geometry/polyline.i"
	@echo "... src/geometry/polyline.s"
	@echo "... src/geometry/triangle.o"
	@echo "... src/geometry/triangle.i"
	@echo "... src/geometry/triangle.s"
	@echo "... src/simulators/mill_tool.o"
	@echo "... src/simulators/mill_tool.i"
	@echo "... src/simulators/mill_tool.s"
	@echo "... src/simulators/sim_mill.o"
	@echo "... src/simulators/sim_mill.i"
	@echo "... src/simulators/sim_mill.s"
	@echo "... src/synthesis/align_blade.o"
	@echo "... src/synthesis/align_blade.i"
	@echo "... src/synthesis/align_blade.s"
	@echo "... src/synthesis/axis_3.o"
	@echo "... src/synthesis/axis_3.i"
	@echo "... src/synthesis/axis_3.s"
	@echo "... src/synthesis/cut.o"
	@echo "... src/synthesis/cut.i"
	@echo "... src/synthesis/cut.s"
	@echo "... src/synthesis/cut_to_gcode.o"
	@echo "... src/synthesis/cut_to_gcode.i"
	@echo "... src/synthesis/cut_to_gcode.s"
	@echo "... src/synthesis/dxf_reader.o"
	@echo "... src/synthesis/dxf_reader.i"
	@echo "... src/synthesis/dxf_reader.s"
	@echo "... src/synthesis/linear_cut.o"
	@echo "... src/synthesis/linear_cut.i"
	@echo "... src/synthesis/linear_cut.s"
	@echo "... src/synthesis/machine.o"
	@echo "... src/synthesis/machine.i"
	@echo "... src/synthesis/machine.s"
	@echo "... src/synthesis/output.o"
	@echo "... src/synthesis/output.i"
	@echo "... src/synthesis/output.s"
	@echo "... src/synthesis/schedule_cuts.o"
	@echo "... src/synthesis/schedule_cuts.i"
	@echo "... src/synthesis/schedule_cuts.s"
	@echo "... src/synthesis/shapes_to_gcode.o"
	@echo "... src/synthesis/shapes_to_gcode.i"
	@echo "... src/synthesis/shapes_to_gcode.s"
	@echo "... src/synthesis/shapes_to_toolpaths.o"
	@echo "... src/synthesis/shapes_to_toolpaths.i"
	@echo "... src/synthesis/shapes_to_toolpaths.s"
	@echo "... src/synthesis/spline_sampling.o"
	@echo "... src/synthesis/spline_sampling.i"
	@echo "... src/synthesis/spline_sampling.s"
	@echo "... src/synthesis/toolpath.o"
	@echo "... src/synthesis/toolpath.i"
	@echo "... src/synthesis/toolpath.s"
	@echo "... src/synthesis/toolpath_generation.o"
	@echo "... src/synthesis/toolpath_generation.i"
	@echo "... src/synthesis/toolpath_generation.s"
	@echo "... src/system/arena_allocator.o"
	@echo "... src/system/arena_allocator.i"
	@echo "... src/system/arena_allocator.s"
	@echo "... src/system/file.o"
	@echo "... src/system/file.i"
	@echo "... src/system/file.s"
	@echo "... src/system/parse_stl.o"
	@echo "... src/system/parse_stl.i"
	@echo "... src/system/parse_stl.s"
	@echo "... src/system/settings.o"
	@echo "... src/system/settings.i"
	@echo "... src/system/settings.s"
	@echo "... src/transformers/feed_changer.o"
	@echo "... src/transformers/feed_changer.i"
	@echo "... src/transformers/feed_changer.s"
	@echo "... src/transformers/retarget.o"
	@echo "... src/transformers/retarget.i"
	@echo "... src/transformers/retarget.s"
	@echo "... test/analysis_tests.o"
	@echo "... test/analysis_tests.i"
	@echo "... test/analysis_tests.s"
	@echo "... test/arc_tests.o"
	@echo "... test/arc_tests.i"
	@echo "... test/arc_tests.s"
	@echo "... test/axis_3_tests.o"
	@echo "... test/axis_3_tests.i"
	@echo "... test/axis_3_tests.s"
	@echo "... test/checker_tests.o"
	@echo "... test/checker_tests.i"
	@echo "... test/checker_tests.s"
	@echo "... test/circular_arc_tests.o"
	@echo "... test/circular_arc_tests.i"
	@echo "... test/circular_arc_tests.s"
	@echo "... test/cut_scheduling_tests.o"
	@echo "... test/cut_scheduling_tests.i"
	@echo "... test/cut_scheduling_tests.s"
	@echo "... test/cut_tests.o"
	@echo "... test/cut_tests.i"
	@echo "... test/cut_tests.s"
	@echo "... test/dxf_to_gcode_tests.o"
	@echo "... test/dxf_to_gcode_tests.i"
	@echo "... test/dxf_to_gcode_tests.s"
	@echo "... test/gcode_to_cuts_tests.o"
	@echo "... test/gcode_to_cuts_tests.i"
	@echo "... test/gcode_to_cuts_tests.s"
	@echo "... test/lexer_tests.o"
	@echo "... test/lexer_tests.i"
	@echo "... test/lexer_tests.s"
	@echo "... test/line_tests.o"
	@echo "... test/line_tests.i"
	@echo "... test/line_tests.s"
	@echo "... test/machine_state_tests.o"
	@echo "... test/machine_state_tests.i"
	@echo "... test/machine_state_tests.s"
	@echo "... test/mill_simulator_tests.o"
	@echo "... test/mill_simulator_tests.i"
	@echo "... test/mill_simulator_tests.s"
	@echo "... test/point_tests.o"
	@echo "... test/point_tests.i"
	@echo "... test/point_tests.s"
	@echo "... test/polygon_tests.o"
	@echo "... test/polygon_tests.i"
	@echo "... test/polygon_tests.s"
	@echo "... test/polyline_tests.o"
	@echo "... test/polyline_tests.i"
	@echo "... test/polyline_tests.s"
	@echo "... test/position_table_tests.o"
	@echo "... test/position_table_tests.i"
	@echo "... test/position_table_tests.s"
	@echo "... test/retargeting_tests.o"
	@echo "... test/retargeting_tests.i"
	@echo "... test/retargeting_tests.s"
	@echo "... test/shapes_to_toolpaths_tests.o"
	@echo "... test/shapes_to_toolpaths_tests.i"
	@echo "... test/shapes_to_toolpaths_tests.s"
	@echo "... test/spline_tests.o"
	@echo "... test/spline_tests.i"
	@echo "... test/spline_tests.s"
	@echo "... test/system_algorithm_tests.o"
	@echo "... test/system_algorithm_tests.i"
	@echo "... test/system_algorithm_tests.s"
	@echo "... test/toolpath_tests.o"
	@echo "... test/toolpath_tests.i"
	@echo "... test/toolpath_tests.s"
	@echo "... test/transformer_tests.o"
	@echo "... test/transformer_tests.i"
	@echo "... test/transformer_tests.s"
	@echo "... test/triangle_tests.o"
	@echo "... test/triangle_tests.i"
	@echo "... test/triangle_tests.s"
	@echo "... test/unfold_tests.o"
	@echo "... test/unfold_tests.i"
	@echo "... test/unfold_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

