# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dillon/CppWorkspace/gca

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dillon/CppWorkspace/gca

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dillon/CppWorkspace/gca/CMakeFiles /Users/dillon/CppWorkspace/gca/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dillon/CppWorkspace/gca/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DataAnimationSubclass

# Build rule for target.
DataAnimationSubclass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DataAnimationSubclass
.PHONY : DataAnimationSubclass

# fast build rule for target.
DataAnimationSubclass/fast:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/build
.PHONY : DataAnimationSubclass/fast

#=============================================================================
# Target rules for targets named all-tests

# Build rule for target.
all-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all-tests
.PHONY : all-tests

# fast build rule for target.
all-tests/fast:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/build
.PHONY : all-tests/fast

#=============================================================================
# Target rules for targets named bmp-prog

# Build rule for target.
bmp-prog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bmp-prog
.PHONY : bmp-prog

# fast build rule for target.
bmp-prog/fast:
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/build
.PHONY : bmp-prog/fast

#=============================================================================
# Target rules for targets named extract-g1-paths

# Build rule for target.
extract-g1-paths: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extract-g1-paths
.PHONY : extract-g1-paths

# fast build rule for target.
extract-g1-paths/fast:
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/build
.PHONY : extract-g1-paths/fast

#=============================================================================
# Target rules for targets named gdiff

# Build rule for target.
gdiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gdiff
.PHONY : gdiff

# fast build rule for target.
gdiff/fast:
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/build
.PHONY : gdiff/fast

#=============================================================================
# Target rules for targets named hello-world

# Build rule for target.
hello-world: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello-world
.PHONY : hello-world

# fast build rule for target.
hello-world/fast:
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/build
.PHONY : hello-world/fast

#=============================================================================
# Target rules for targets named hole-optimizer

# Build rule for target.
hole-optimizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hole-optimizer
.PHONY : hole-optimizer

# fast build rule for target.
hole-optimizer/fast:
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/build
.PHONY : hole-optimizer/fast

#=============================================================================
# Target rules for targets named print-knife-hacks

# Build rule for target.
print-knife-hacks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 print-knife-hacks
.PHONY : print-knife-hacks

# fast build rule for target.
print-knife-hacks/fast:
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/build
.PHONY : print-knife-hacks/fast

#=============================================================================
# Target rules for targets named print-strap

# Build rule for target.
print-strap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 print-strap
.PHONY : print-strap

# fast build rule for target.
print-strap/fast:
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/build
.PHONY : print-strap/fast

#=============================================================================
# Target rules for targets named simple-deepen

# Build rule for target.
simple-deepen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple-deepen
.PHONY : simple-deepen

# fast build rule for target.
simple-deepen/fast:
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/build
.PHONY : simple-deepen/fast

#=============================================================================
# Target rules for targets named z-abstract

# Build rule for target.
z-abstract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 z-abstract
.PHONY : z-abstract

# fast build rule for target.
z-abstract/fast:
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/build
.PHONY : z-abstract/fast

examples/DataAnimationSubclass.o: examples/DataAnimationSubclass.cpp.o

.PHONY : examples/DataAnimationSubclass.o

# target to build an object file
examples/DataAnimationSubclass.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/examples/DataAnimationSubclass.cpp.o
.PHONY : examples/DataAnimationSubclass.cpp.o

examples/DataAnimationSubclass.i: examples/DataAnimationSubclass.cpp.i

.PHONY : examples/DataAnimationSubclass.i

# target to preprocess a source file
examples/DataAnimationSubclass.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/examples/DataAnimationSubclass.cpp.i
.PHONY : examples/DataAnimationSubclass.cpp.i

examples/DataAnimationSubclass.s: examples/DataAnimationSubclass.cpp.s

.PHONY : examples/DataAnimationSubclass.s

# target to generate assembly for a file
examples/DataAnimationSubclass.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/examples/DataAnimationSubclass.cpp.s
.PHONY : examples/DataAnimationSubclass.cpp.s

examples/bmp_prog.o: examples/bmp_prog.cpp.o

.PHONY : examples/bmp_prog.o

# target to build an object file
examples/bmp_prog.cpp.o:
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/examples/bmp_prog.cpp.o
.PHONY : examples/bmp_prog.cpp.o

examples/bmp_prog.i: examples/bmp_prog.cpp.i

.PHONY : examples/bmp_prog.i

# target to preprocess a source file
examples/bmp_prog.cpp.i:
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/examples/bmp_prog.cpp.i
.PHONY : examples/bmp_prog.cpp.i

examples/bmp_prog.s: examples/bmp_prog.cpp.s

.PHONY : examples/bmp_prog.s

# target to generate assembly for a file
examples/bmp_prog.cpp.s:
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/examples/bmp_prog.cpp.s
.PHONY : examples/bmp_prog.cpp.s

examples/extract_g1_paths.o: examples/extract_g1_paths.cpp.o

.PHONY : examples/extract_g1_paths.o

# target to build an object file
examples/extract_g1_paths.cpp.o:
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/examples/extract_g1_paths.cpp.o
.PHONY : examples/extract_g1_paths.cpp.o

examples/extract_g1_paths.i: examples/extract_g1_paths.cpp.i

.PHONY : examples/extract_g1_paths.i

# target to preprocess a source file
examples/extract_g1_paths.cpp.i:
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/examples/extract_g1_paths.cpp.i
.PHONY : examples/extract_g1_paths.cpp.i

examples/extract_g1_paths.s: examples/extract_g1_paths.cpp.s

.PHONY : examples/extract_g1_paths.s

# target to generate assembly for a file
examples/extract_g1_paths.cpp.s:
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/examples/extract_g1_paths.cpp.s
.PHONY : examples/extract_g1_paths.cpp.s

examples/gdiff.o: examples/gdiff.cpp.o

.PHONY : examples/gdiff.o

# target to build an object file
examples/gdiff.cpp.o:
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/examples/gdiff.cpp.o
.PHONY : examples/gdiff.cpp.o

examples/gdiff.i: examples/gdiff.cpp.i

.PHONY : examples/gdiff.i

# target to preprocess a source file
examples/gdiff.cpp.i:
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/examples/gdiff.cpp.i
.PHONY : examples/gdiff.cpp.i

examples/gdiff.s: examples/gdiff.cpp.s

.PHONY : examples/gdiff.s

# target to generate assembly for a file
examples/gdiff.cpp.s:
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/examples/gdiff.cpp.s
.PHONY : examples/gdiff.cpp.s

examples/hello_world.o: examples/hello_world.cpp.o

.PHONY : examples/hello_world.o

# target to build an object file
examples/hello_world.cpp.o:
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/examples/hello_world.cpp.o
.PHONY : examples/hello_world.cpp.o

examples/hello_world.i: examples/hello_world.cpp.i

.PHONY : examples/hello_world.i

# target to preprocess a source file
examples/hello_world.cpp.i:
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/examples/hello_world.cpp.i
.PHONY : examples/hello_world.cpp.i

examples/hello_world.s: examples/hello_world.cpp.s

.PHONY : examples/hello_world.s

# target to generate assembly for a file
examples/hello_world.cpp.s:
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/examples/hello_world.cpp.s
.PHONY : examples/hello_world.cpp.s

examples/hole_optimizer.o: examples/hole_optimizer.cpp.o

.PHONY : examples/hole_optimizer.o

# target to build an object file
examples/hole_optimizer.cpp.o:
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/examples/hole_optimizer.cpp.o
.PHONY : examples/hole_optimizer.cpp.o

examples/hole_optimizer.i: examples/hole_optimizer.cpp.i

.PHONY : examples/hole_optimizer.i

# target to preprocess a source file
examples/hole_optimizer.cpp.i:
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/examples/hole_optimizer.cpp.i
.PHONY : examples/hole_optimizer.cpp.i

examples/hole_optimizer.s: examples/hole_optimizer.cpp.s

.PHONY : examples/hole_optimizer.s

# target to generate assembly for a file
examples/hole_optimizer.cpp.s:
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/examples/hole_optimizer.cpp.s
.PHONY : examples/hole_optimizer.cpp.s

examples/print_knife_hacks.o: examples/print_knife_hacks.cpp.o

.PHONY : examples/print_knife_hacks.o

# target to build an object file
examples/print_knife_hacks.cpp.o:
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/examples/print_knife_hacks.cpp.o
.PHONY : examples/print_knife_hacks.cpp.o

examples/print_knife_hacks.i: examples/print_knife_hacks.cpp.i

.PHONY : examples/print_knife_hacks.i

# target to preprocess a source file
examples/print_knife_hacks.cpp.i:
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/examples/print_knife_hacks.cpp.i
.PHONY : examples/print_knife_hacks.cpp.i

examples/print_knife_hacks.s: examples/print_knife_hacks.cpp.s

.PHONY : examples/print_knife_hacks.s

# target to generate assembly for a file
examples/print_knife_hacks.cpp.s:
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/examples/print_knife_hacks.cpp.s
.PHONY : examples/print_knife_hacks.cpp.s

examples/print_strap.o: examples/print_strap.cpp.o

.PHONY : examples/print_strap.o

# target to build an object file
examples/print_strap.cpp.o:
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/examples/print_strap.cpp.o
.PHONY : examples/print_strap.cpp.o

examples/print_strap.i: examples/print_strap.cpp.i

.PHONY : examples/print_strap.i

# target to preprocess a source file
examples/print_strap.cpp.i:
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/examples/print_strap.cpp.i
.PHONY : examples/print_strap.cpp.i

examples/print_strap.s: examples/print_strap.cpp.s

.PHONY : examples/print_strap.s

# target to generate assembly for a file
examples/print_strap.cpp.s:
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/examples/print_strap.cpp.s
.PHONY : examples/print_strap.cpp.s

examples/simple_deepen.o: examples/simple_deepen.cpp.o

.PHONY : examples/simple_deepen.o

# target to build an object file
examples/simple_deepen.cpp.o:
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/examples/simple_deepen.cpp.o
.PHONY : examples/simple_deepen.cpp.o

examples/simple_deepen.i: examples/simple_deepen.cpp.i

.PHONY : examples/simple_deepen.i

# target to preprocess a source file
examples/simple_deepen.cpp.i:
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/examples/simple_deepen.cpp.i
.PHONY : examples/simple_deepen.cpp.i

examples/simple_deepen.s: examples/simple_deepen.cpp.s

.PHONY : examples/simple_deepen.s

# target to generate assembly for a file
examples/simple_deepen.cpp.s:
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/examples/simple_deepen.cpp.s
.PHONY : examples/simple_deepen.cpp.s

examples/z_abstract.o: examples/z_abstract.cpp.o

.PHONY : examples/z_abstract.o

# target to build an object file
examples/z_abstract.cpp.o:
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/examples/z_abstract.cpp.o
.PHONY : examples/z_abstract.cpp.o

examples/z_abstract.i: examples/z_abstract.cpp.i

.PHONY : examples/z_abstract.i

# target to preprocess a source file
examples/z_abstract.cpp.i:
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/examples/z_abstract.cpp.i
.PHONY : examples/z_abstract.cpp.i

examples/z_abstract.s: examples/z_abstract.cpp.s

.PHONY : examples/z_abstract.s

# target to generate assembly for a file
examples/z_abstract.cpp.s:
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/examples/z_abstract.cpp.s
.PHONY : examples/z_abstract.cpp.s

src/analysis/extract_cuts.o: src/analysis/extract_cuts.cpp.o

.PHONY : src/analysis/extract_cuts.o

# target to build an object file
src/analysis/extract_cuts.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/analysis/extract_cuts.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/analysis/extract_cuts.cpp.o
.PHONY : src/analysis/extract_cuts.cpp.o

src/analysis/extract_cuts.i: src/analysis/extract_cuts.cpp.i

.PHONY : src/analysis/extract_cuts.i

# target to preprocess a source file
src/analysis/extract_cuts.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/analysis/extract_cuts.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/analysis/extract_cuts.cpp.i
.PHONY : src/analysis/extract_cuts.cpp.i

src/analysis/extract_cuts.s: src/analysis/extract_cuts.cpp.s

.PHONY : src/analysis/extract_cuts.s

# target to generate assembly for a file
src/analysis/extract_cuts.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/analysis/extract_cuts.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/analysis/extract_cuts.cpp.s
.PHONY : src/analysis/extract_cuts.cpp.s

src/core/arena_allocator.o: src/core/arena_allocator.cpp.o

.PHONY : src/core/arena_allocator.o

# target to build an object file
src/core/arena_allocator.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/arena_allocator.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/arena_allocator.cpp.o
.PHONY : src/core/arena_allocator.cpp.o

src/core/arena_allocator.i: src/core/arena_allocator.cpp.i

.PHONY : src/core/arena_allocator.i

# target to preprocess a source file
src/core/arena_allocator.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/arena_allocator.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/arena_allocator.cpp.i
.PHONY : src/core/arena_allocator.cpp.i

src/core/arena_allocator.s: src/core/arena_allocator.cpp.s

.PHONY : src/core/arena_allocator.s

# target to generate assembly for a file
src/core/arena_allocator.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/arena_allocator.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/arena_allocator.cpp.s
.PHONY : src/core/arena_allocator.cpp.s

src/core/context.o: src/core/context.cpp.o

.PHONY : src/core/context.o

# target to build an object file
src/core/context.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/context.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/context.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/context.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/context.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/context.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/context.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/context.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/context.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/context.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/context.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/context.cpp.o
.PHONY : src/core/context.cpp.o

src/core/context.i: src/core/context.cpp.i

.PHONY : src/core/context.i

# target to preprocess a source file
src/core/context.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/context.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/context.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/context.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/context.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/context.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/context.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/context.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/context.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/context.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/context.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/context.cpp.i
.PHONY : src/core/context.cpp.i

src/core/context.s: src/core/context.cpp.s

.PHONY : src/core/context.s

# target to generate assembly for a file
src/core/context.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/context.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/context.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/context.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/context.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/context.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/context.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/context.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/context.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/context.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/context.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/context.cpp.s
.PHONY : src/core/context.cpp.s

src/core/gprog.o: src/core/gprog.cpp.o

.PHONY : src/core/gprog.o

# target to build an object file
src/core/gprog.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/gprog.cpp.o
.PHONY : src/core/gprog.cpp.o

src/core/gprog.i: src/core/gprog.cpp.i

.PHONY : src/core/gprog.i

# target to preprocess a source file
src/core/gprog.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/gprog.cpp.i
.PHONY : src/core/gprog.cpp.i

src/core/gprog.s: src/core/gprog.cpp.s

.PHONY : src/core/gprog.s

# target to generate assembly for a file
src/core/gprog.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/gprog.cpp.s
.PHONY : src/core/gprog.cpp.s

src/core/instrs/instr.o: src/core/instrs/instr.cpp.o

.PHONY : src/core/instrs/instr.o

# target to build an object file
src/core/instrs/instr.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/instrs/instr.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/instrs/instr.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/instrs/instr.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/instrs/instr.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/instrs/instr.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/instrs/instr.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/instrs/instr.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/instrs/instr.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/instrs/instr.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/instrs/instr.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/instrs/instr.cpp.o
.PHONY : src/core/instrs/instr.cpp.o

src/core/instrs/instr.i: src/core/instrs/instr.cpp.i

.PHONY : src/core/instrs/instr.i

# target to preprocess a source file
src/core/instrs/instr.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/instrs/instr.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/instrs/instr.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/instrs/instr.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/instrs/instr.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/instrs/instr.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/instrs/instr.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/instrs/instr.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/instrs/instr.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/instrs/instr.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/instrs/instr.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/instrs/instr.cpp.i
.PHONY : src/core/instrs/instr.cpp.i

src/core/instrs/instr.s: src/core/instrs/instr.cpp.s

.PHONY : src/core/instrs/instr.s

# target to generate assembly for a file
src/core/instrs/instr.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/instrs/instr.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/instrs/instr.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/instrs/instr.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/instrs/instr.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/instrs/instr.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/instrs/instr.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/instrs/instr.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/instrs/instr.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/instrs/instr.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/instrs/instr.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/instrs/instr.cpp.s
.PHONY : src/core/instrs/instr.cpp.s

src/core/parser.o: src/core/parser.cpp.o

.PHONY : src/core/parser.o

# target to build an object file
src/core/parser.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/parser.cpp.o
.PHONY : src/core/parser.cpp.o

src/core/parser.i: src/core/parser.cpp.i

.PHONY : src/core/parser.i

# target to preprocess a source file
src/core/parser.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/parser.cpp.i
.PHONY : src/core/parser.cpp.i

src/core/parser.s: src/core/parser.cpp.s

.PHONY : src/core/parser.s

# target to generate assembly for a file
src/core/parser.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/parser.cpp.s
.PHONY : src/core/parser.cpp.s

src/core/pass.o: src/core/pass.cpp.o

.PHONY : src/core/pass.o

# target to build an object file
src/core/pass.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/pass.cpp.o
.PHONY : src/core/pass.cpp.o

src/core/pass.i: src/core/pass.cpp.i

.PHONY : src/core/pass.i

# target to preprocess a source file
src/core/pass.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/pass.cpp.i
.PHONY : src/core/pass.cpp.i

src/core/pass.s: src/core/pass.cpp.s

.PHONY : src/core/pass.s

# target to generate assembly for a file
src/core/pass.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/pass.cpp.s
.PHONY : src/core/pass.cpp.s

src/core/value.o: src/core/value.cpp.o

.PHONY : src/core/value.o

# target to build an object file
src/core/value.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/value.cpp.o
.PHONY : src/core/value.cpp.o

src/core/value.i: src/core/value.cpp.i

.PHONY : src/core/value.i

# target to preprocess a source file
src/core/value.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/value.cpp.i
.PHONY : src/core/value.cpp.i

src/core/value.s: src/core/value.cpp.s

.PHONY : src/core/value.s

# target to generate assembly for a file
src/core/value.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/core/value.cpp.s
.PHONY : src/core/value.cpp.s

src/geometry/point.o: src/geometry/point.cpp.o

.PHONY : src/geometry/point.o

# target to build an object file
src/geometry/point.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/geometry/point.cpp.o
.PHONY : src/geometry/point.cpp.o

src/geometry/point.i: src/geometry/point.cpp.i

.PHONY : src/geometry/point.i

# target to preprocess a source file
src/geometry/point.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/geometry/point.cpp.i
.PHONY : src/geometry/point.cpp.i

src/geometry/point.s: src/geometry/point.cpp.s

.PHONY : src/geometry/point.s

# target to generate assembly for a file
src/geometry/point.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/geometry/point.cpp.s
.PHONY : src/geometry/point.cpp.s

src/simulators/mill_tool.o: src/simulators/mill_tool.cpp.o

.PHONY : src/simulators/mill_tool.o

# target to build an object file
src/simulators/mill_tool.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/simulators/mill_tool.cpp.o
.PHONY : src/simulators/mill_tool.cpp.o

src/simulators/mill_tool.i: src/simulators/mill_tool.cpp.i

.PHONY : src/simulators/mill_tool.i

# target to preprocess a source file
src/simulators/mill_tool.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/simulators/mill_tool.cpp.i
.PHONY : src/simulators/mill_tool.cpp.i

src/simulators/mill_tool.s: src/simulators/mill_tool.cpp.s

.PHONY : src/simulators/mill_tool.s

# target to generate assembly for a file
src/simulators/mill_tool.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/simulators/mill_tool.cpp.s
.PHONY : src/simulators/mill_tool.cpp.s

src/simulators/sim_mill.o: src/simulators/sim_mill.cpp.o

.PHONY : src/simulators/sim_mill.o

# target to build an object file
src/simulators/sim_mill.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/simulators/sim_mill.cpp.o
.PHONY : src/simulators/sim_mill.cpp.o

src/simulators/sim_mill.i: src/simulators/sim_mill.cpp.i

.PHONY : src/simulators/sim_mill.i

# target to preprocess a source file
src/simulators/sim_mill.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/simulators/sim_mill.cpp.i
.PHONY : src/simulators/sim_mill.cpp.i

src/simulators/sim_mill.s: src/simulators/sim_mill.cpp.s

.PHONY : src/simulators/sim_mill.s

# target to generate assembly for a file
src/simulators/sim_mill.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/simulators/sim_mill.cpp.s
.PHONY : src/simulators/sim_mill.cpp.s

src/synthesis/align_blade.o: src/synthesis/align_blade.cpp.o

.PHONY : src/synthesis/align_blade.o

# target to build an object file
src/synthesis/align_blade.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/synthesis/align_blade.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/synthesis/align_blade.cpp.o
.PHONY : src/synthesis/align_blade.cpp.o

src/synthesis/align_blade.i: src/synthesis/align_blade.cpp.i

.PHONY : src/synthesis/align_blade.i

# target to preprocess a source file
src/synthesis/align_blade.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/synthesis/align_blade.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/synthesis/align_blade.cpp.i
.PHONY : src/synthesis/align_blade.cpp.i

src/synthesis/align_blade.s: src/synthesis/align_blade.cpp.s

.PHONY : src/synthesis/align_blade.s

# target to generate assembly for a file
src/synthesis/align_blade.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/synthesis/align_blade.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/synthesis/align_blade.cpp.s
.PHONY : src/synthesis/align_blade.cpp.s

src/synthesis/output.o: src/synthesis/output.cpp.o

.PHONY : src/synthesis/output.o

# target to build an object file
src/synthesis/output.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/synthesis/output.cpp.o
.PHONY : src/synthesis/output.cpp.o

src/synthesis/output.i: src/synthesis/output.cpp.i

.PHONY : src/synthesis/output.i

# target to preprocess a source file
src/synthesis/output.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/synthesis/output.cpp.i
.PHONY : src/synthesis/output.cpp.i

src/synthesis/output.s: src/synthesis/output.cpp.s

.PHONY : src/synthesis/output.s

# target to generate assembly for a file
src/synthesis/output.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/synthesis/output.cpp.s
.PHONY : src/synthesis/output.cpp.s

src/system/bmp_output.o: src/system/bmp_output.cpp.o

.PHONY : src/system/bmp_output.o

# target to build an object file
src/system/bmp_output.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/system/bmp_output.cpp.o
.PHONY : src/system/bmp_output.cpp.o

src/system/bmp_output.i: src/system/bmp_output.cpp.i

.PHONY : src/system/bmp_output.i

# target to preprocess a source file
src/system/bmp_output.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/system/bmp_output.cpp.i
.PHONY : src/system/bmp_output.cpp.i

src/system/bmp_output.s: src/system/bmp_output.cpp.s

.PHONY : src/system/bmp_output.s

# target to generate assembly for a file
src/system/bmp_output.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/system/bmp_output.cpp.s
.PHONY : src/system/bmp_output.cpp.s

src/transformers/scale_xyz.o: src/transformers/scale_xyz.cpp.o

.PHONY : src/transformers/scale_xyz.o

# target to build an object file
src/transformers/scale_xyz.cpp.o:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/transformers/scale_xyz.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/transformers/scale_xyz.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/transformers/scale_xyz.cpp.o
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/transformers/scale_xyz.cpp.o
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/transformers/scale_xyz.cpp.o
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/transformers/scale_xyz.cpp.o
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/transformers/scale_xyz.cpp.o
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/transformers/scale_xyz.cpp.o
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/transformers/scale_xyz.cpp.o
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/transformers/scale_xyz.cpp.o
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/transformers/scale_xyz.cpp.o
.PHONY : src/transformers/scale_xyz.cpp.o

src/transformers/scale_xyz.i: src/transformers/scale_xyz.cpp.i

.PHONY : src/transformers/scale_xyz.i

# target to preprocess a source file
src/transformers/scale_xyz.cpp.i:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/transformers/scale_xyz.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/transformers/scale_xyz.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/transformers/scale_xyz.cpp.i
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/transformers/scale_xyz.cpp.i
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/transformers/scale_xyz.cpp.i
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/transformers/scale_xyz.cpp.i
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/transformers/scale_xyz.cpp.i
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/transformers/scale_xyz.cpp.i
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/transformers/scale_xyz.cpp.i
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/transformers/scale_xyz.cpp.i
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/transformers/scale_xyz.cpp.i
.PHONY : src/transformers/scale_xyz.cpp.i

src/transformers/scale_xyz.s: src/transformers/scale_xyz.cpp.s

.PHONY : src/transformers/scale_xyz.s

# target to generate assembly for a file
src/transformers/scale_xyz.cpp.s:
	$(MAKE) -f CMakeFiles/DataAnimationSubclass.dir/build.make CMakeFiles/DataAnimationSubclass.dir/src/transformers/scale_xyz.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/transformers/scale_xyz.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/transformers/scale_xyz.cpp.s
	$(MAKE) -f CMakeFiles/extract-g1-paths.dir/build.make CMakeFiles/extract-g1-paths.dir/src/transformers/scale_xyz.cpp.s
	$(MAKE) -f CMakeFiles/gdiff.dir/build.make CMakeFiles/gdiff.dir/src/transformers/scale_xyz.cpp.s
	$(MAKE) -f CMakeFiles/hello-world.dir/build.make CMakeFiles/hello-world.dir/src/transformers/scale_xyz.cpp.s
	$(MAKE) -f CMakeFiles/hole-optimizer.dir/build.make CMakeFiles/hole-optimizer.dir/src/transformers/scale_xyz.cpp.s
	$(MAKE) -f CMakeFiles/print-knife-hacks.dir/build.make CMakeFiles/print-knife-hacks.dir/src/transformers/scale_xyz.cpp.s
	$(MAKE) -f CMakeFiles/print-strap.dir/build.make CMakeFiles/print-strap.dir/src/transformers/scale_xyz.cpp.s
	$(MAKE) -f CMakeFiles/simple-deepen.dir/build.make CMakeFiles/simple-deepen.dir/src/transformers/scale_xyz.cpp.s
	$(MAKE) -f CMakeFiles/z-abstract.dir/build.make CMakeFiles/z-abstract.dir/src/transformers/scale_xyz.cpp.s
.PHONY : src/transformers/scale_xyz.cpp.s

test/analysis_tests.o: test/analysis_tests.cpp.o

.PHONY : test/analysis_tests.o

# target to build an object file
test/analysis_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/analysis_tests.cpp.o
.PHONY : test/analysis_tests.cpp.o

test/analysis_tests.i: test/analysis_tests.cpp.i

.PHONY : test/analysis_tests.i

# target to preprocess a source file
test/analysis_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/analysis_tests.cpp.i
.PHONY : test/analysis_tests.cpp.i

test/analysis_tests.s: test/analysis_tests.cpp.s

.PHONY : test/analysis_tests.s

# target to generate assembly for a file
test/analysis_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/analysis_tests.cpp.s
.PHONY : test/analysis_tests.cpp.s

test/checker_tests.o: test/checker_tests.cpp.o

.PHONY : test/checker_tests.o

# target to build an object file
test/checker_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/checker_tests.cpp.o
.PHONY : test/checker_tests.cpp.o

test/checker_tests.i: test/checker_tests.cpp.i

.PHONY : test/checker_tests.i

# target to preprocess a source file
test/checker_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/checker_tests.cpp.i
.PHONY : test/checker_tests.cpp.i

test/checker_tests.s: test/checker_tests.cpp.s

.PHONY : test/checker_tests.s

# target to generate assembly for a file
test/checker_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/checker_tests.cpp.s
.PHONY : test/checker_tests.cpp.s

test/cut_tests.o: test/cut_tests.cpp.o

.PHONY : test/cut_tests.o

# target to build an object file
test/cut_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_tests.cpp.o
.PHONY : test/cut_tests.cpp.o

test/cut_tests.i: test/cut_tests.cpp.i

.PHONY : test/cut_tests.i

# target to preprocess a source file
test/cut_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_tests.cpp.i
.PHONY : test/cut_tests.cpp.i

test/cut_tests.s: test/cut_tests.cpp.s

.PHONY : test/cut_tests.s

# target to generate assembly for a file
test/cut_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_tests.cpp.s
.PHONY : test/cut_tests.cpp.s

test/line_tests.o: test/line_tests.cpp.o

.PHONY : test/line_tests.o

# target to build an object file
test/line_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/line_tests.cpp.o
.PHONY : test/line_tests.cpp.o

test/line_tests.i: test/line_tests.cpp.i

.PHONY : test/line_tests.i

# target to preprocess a source file
test/line_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/line_tests.cpp.i
.PHONY : test/line_tests.cpp.i

test/line_tests.s: test/line_tests.cpp.s

.PHONY : test/line_tests.s

# target to generate assembly for a file
test/line_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/line_tests.cpp.s
.PHONY : test/line_tests.cpp.s

test/mill_simulator_tests.o: test/mill_simulator_tests.cpp.o

.PHONY : test/mill_simulator_tests.o

# target to build an object file
test/mill_simulator_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/mill_simulator_tests.cpp.o
.PHONY : test/mill_simulator_tests.cpp.o

test/mill_simulator_tests.i: test/mill_simulator_tests.cpp.i

.PHONY : test/mill_simulator_tests.i

# target to preprocess a source file
test/mill_simulator_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/mill_simulator_tests.cpp.i
.PHONY : test/mill_simulator_tests.cpp.i

test/mill_simulator_tests.s: test/mill_simulator_tests.cpp.s

.PHONY : test/mill_simulator_tests.s

# target to generate assembly for a file
test/mill_simulator_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/mill_simulator_tests.cpp.s
.PHONY : test/mill_simulator_tests.cpp.s

test/parse_tests.o: test/parse_tests.cpp.o

.PHONY : test/parse_tests.o

# target to build an object file
test/parse_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/parse_tests.cpp.o
.PHONY : test/parse_tests.cpp.o

test/parse_tests.i: test/parse_tests.cpp.i

.PHONY : test/parse_tests.i

# target to preprocess a source file
test/parse_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/parse_tests.cpp.i
.PHONY : test/parse_tests.cpp.i

test/parse_tests.s: test/parse_tests.cpp.s

.PHONY : test/parse_tests.s

# target to generate assembly for a file
test/parse_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/parse_tests.cpp.s
.PHONY : test/parse_tests.cpp.s

test/point_tests.o: test/point_tests.cpp.o

.PHONY : test/point_tests.o

# target to build an object file
test/point_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/point_tests.cpp.o
.PHONY : test/point_tests.cpp.o

test/point_tests.i: test/point_tests.cpp.i

.PHONY : test/point_tests.i

# target to preprocess a source file
test/point_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/point_tests.cpp.i
.PHONY : test/point_tests.cpp.i

test/point_tests.s: test/point_tests.cpp.s

.PHONY : test/point_tests.s

# target to generate assembly for a file
test/point_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/point_tests.cpp.s
.PHONY : test/point_tests.cpp.s

test/transformer_tests.o: test/transformer_tests.cpp.o

.PHONY : test/transformer_tests.o

# target to build an object file
test/transformer_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/transformer_tests.cpp.o
.PHONY : test/transformer_tests.cpp.o

test/transformer_tests.i: test/transformer_tests.cpp.i

.PHONY : test/transformer_tests.i

# target to preprocess a source file
test/transformer_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/transformer_tests.cpp.i
.PHONY : test/transformer_tests.cpp.i

test/transformer_tests.s: test/transformer_tests.cpp.s

.PHONY : test/transformer_tests.s

# target to generate assembly for a file
test/transformer_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/transformer_tests.cpp.s
.PHONY : test/transformer_tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... gdiff"
	@echo "... extract-g1-paths"
	@echo "... hello-world"
	@echo "... simple-deepen"
	@echo "... print-knife-hacks"
	@echo "... hole-optimizer"
	@echo "... z-abstract"
	@echo "... DataAnimationSubclass"
	@echo "... bmp-prog"
	@echo "... print-strap"
	@echo "... all-tests"
	@echo "... examples/DataAnimationSubclass.o"
	@echo "... examples/DataAnimationSubclass.i"
	@echo "... examples/DataAnimationSubclass.s"
	@echo "... examples/bmp_prog.o"
	@echo "... examples/bmp_prog.i"
	@echo "... examples/bmp_prog.s"
	@echo "... examples/extract_g1_paths.o"
	@echo "... examples/extract_g1_paths.i"
	@echo "... examples/extract_g1_paths.s"
	@echo "... examples/gdiff.o"
	@echo "... examples/gdiff.i"
	@echo "... examples/gdiff.s"
	@echo "... examples/hello_world.o"
	@echo "... examples/hello_world.i"
	@echo "... examples/hello_world.s"
	@echo "... examples/hole_optimizer.o"
	@echo "... examples/hole_optimizer.i"
	@echo "... examples/hole_optimizer.s"
	@echo "... examples/print_knife_hacks.o"
	@echo "... examples/print_knife_hacks.i"
	@echo "... examples/print_knife_hacks.s"
	@echo "... examples/print_strap.o"
	@echo "... examples/print_strap.i"
	@echo "... examples/print_strap.s"
	@echo "... examples/simple_deepen.o"
	@echo "... examples/simple_deepen.i"
	@echo "... examples/simple_deepen.s"
	@echo "... examples/z_abstract.o"
	@echo "... examples/z_abstract.i"
	@echo "... examples/z_abstract.s"
	@echo "... src/analysis/extract_cuts.o"
	@echo "... src/analysis/extract_cuts.i"
	@echo "... src/analysis/extract_cuts.s"
	@echo "... src/core/arena_allocator.o"
	@echo "... src/core/arena_allocator.i"
	@echo "... src/core/arena_allocator.s"
	@echo "... src/core/context.o"
	@echo "... src/core/context.i"
	@echo "... src/core/context.s"
	@echo "... src/core/gprog.o"
	@echo "... src/core/gprog.i"
	@echo "... src/core/gprog.s"
	@echo "... src/core/instrs/instr.o"
	@echo "... src/core/instrs/instr.i"
	@echo "... src/core/instrs/instr.s"
	@echo "... src/core/parser.o"
	@echo "... src/core/parser.i"
	@echo "... src/core/parser.s"
	@echo "... src/core/pass.o"
	@echo "... src/core/pass.i"
	@echo "... src/core/pass.s"
	@echo "... src/core/value.o"
	@echo "... src/core/value.i"
	@echo "... src/core/value.s"
	@echo "... src/geometry/point.o"
	@echo "... src/geometry/point.i"
	@echo "... src/geometry/point.s"
	@echo "... src/simulators/mill_tool.o"
	@echo "... src/simulators/mill_tool.i"
	@echo "... src/simulators/mill_tool.s"
	@echo "... src/simulators/sim_mill.o"
	@echo "... src/simulators/sim_mill.i"
	@echo "... src/simulators/sim_mill.s"
	@echo "... src/synthesis/align_blade.o"
	@echo "... src/synthesis/align_blade.i"
	@echo "... src/synthesis/align_blade.s"
	@echo "... src/synthesis/output.o"
	@echo "... src/synthesis/output.i"
	@echo "... src/synthesis/output.s"
	@echo "... src/system/bmp_output.o"
	@echo "... src/system/bmp_output.i"
	@echo "... src/system/bmp_output.s"
	@echo "... src/transformers/scale_xyz.o"
	@echo "... src/transformers/scale_xyz.i"
	@echo "... src/transformers/scale_xyz.s"
	@echo "... test/analysis_tests.o"
	@echo "... test/analysis_tests.i"
	@echo "... test/analysis_tests.s"
	@echo "... test/checker_tests.o"
	@echo "... test/checker_tests.i"
	@echo "... test/checker_tests.s"
	@echo "... test/cut_tests.o"
	@echo "... test/cut_tests.i"
	@echo "... test/cut_tests.s"
	@echo "... test/line_tests.o"
	@echo "... test/line_tests.i"
	@echo "... test/line_tests.s"
	@echo "... test/mill_simulator_tests.o"
	@echo "... test/mill_simulator_tests.i"
	@echo "... test/mill_simulator_tests.s"
	@echo "... test/parse_tests.o"
	@echo "... test/parse_tests.i"
	@echo "... test/parse_tests.s"
	@echo "... test/point_tests.o"
	@echo "... test/point_tests.i"
	@echo "... test/point_tests.s"
	@echo "... test/transformer_tests.o"
	@echo "... test/transformer_tests.i"
	@echo "... test/transformer_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

