# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dillon/CppWorkspace/gca

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dillon/CppWorkspace/gca

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dillon/CppWorkspace/gca/CMakeFiles /Users/dillon/CppWorkspace/gca/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dillon/CppWorkspace/gca/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TriangulateTerrainMap

# Build rule for target.
TriangulateTerrainMap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TriangulateTerrainMap
.PHONY : TriangulateTerrainMap

# fast build rule for target.
TriangulateTerrainMap/fast:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/build
.PHONY : TriangulateTerrainMap/fast

#=============================================================================
# Target rules for targets named all-tests

# Build rule for target.
all-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all-tests
.PHONY : all-tests

# fast build rule for target.
all-tests/fast:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/build
.PHONY : all-tests/fast

#=============================================================================
# Target rules for targets named bmp-prog

# Build rule for target.
bmp-prog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bmp-prog
.PHONY : bmp-prog

# fast build rule for target.
bmp-prog/fast:
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/build
.PHONY : bmp-prog/fast

examples/TriangulateTerrainMap.o: examples/TriangulateTerrainMap.cxx.o

.PHONY : examples/TriangulateTerrainMap.o

# target to build an object file
examples/TriangulateTerrainMap.cxx.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/examples/TriangulateTerrainMap.cxx.o
.PHONY : examples/TriangulateTerrainMap.cxx.o

examples/TriangulateTerrainMap.i: examples/TriangulateTerrainMap.cxx.i

.PHONY : examples/TriangulateTerrainMap.i

# target to preprocess a source file
examples/TriangulateTerrainMap.cxx.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/examples/TriangulateTerrainMap.cxx.i
.PHONY : examples/TriangulateTerrainMap.cxx.i

examples/TriangulateTerrainMap.s: examples/TriangulateTerrainMap.cxx.s

.PHONY : examples/TriangulateTerrainMap.s

# target to generate assembly for a file
examples/TriangulateTerrainMap.cxx.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/examples/TriangulateTerrainMap.cxx.s
.PHONY : examples/TriangulateTerrainMap.cxx.s

examples/bmp_prog.o: examples/bmp_prog.cpp.o

.PHONY : examples/bmp_prog.o

# target to build an object file
examples/bmp_prog.cpp.o:
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/examples/bmp_prog.cpp.o
.PHONY : examples/bmp_prog.cpp.o

examples/bmp_prog.i: examples/bmp_prog.cpp.i

.PHONY : examples/bmp_prog.i

# target to preprocess a source file
examples/bmp_prog.cpp.i:
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/examples/bmp_prog.cpp.i
.PHONY : examples/bmp_prog.cpp.i

examples/bmp_prog.s: examples/bmp_prog.cpp.s

.PHONY : examples/bmp_prog.s

# target to generate assembly for a file
examples/bmp_prog.cpp.s:
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/examples/bmp_prog.cpp.s
.PHONY : examples/bmp_prog.cpp.s

src/core/gprog.o: src/core/gprog.cpp.o

.PHONY : src/core/gprog.o

# target to build an object file
src/core/gprog.cpp.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/gprog.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/gprog.cpp.o
.PHONY : src/core/gprog.cpp.o

src/core/gprog.i: src/core/gprog.cpp.i

.PHONY : src/core/gprog.i

# target to preprocess a source file
src/core/gprog.cpp.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/gprog.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/gprog.cpp.i
.PHONY : src/core/gprog.cpp.i

src/core/gprog.s: src/core/gprog.cpp.s

.PHONY : src/core/gprog.s

# target to generate assembly for a file
src/core/gprog.cpp.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/gprog.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/gprog.cpp.s
.PHONY : src/core/gprog.cpp.s

src/core/instr.o: src/core/instr.cpp.o

.PHONY : src/core/instr.o

# target to build an object file
src/core/instr.cpp.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/instr.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/instr.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/instr.cpp.o
.PHONY : src/core/instr.cpp.o

src/core/instr.i: src/core/instr.cpp.i

.PHONY : src/core/instr.i

# target to preprocess a source file
src/core/instr.cpp.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/instr.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/instr.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/instr.cpp.i
.PHONY : src/core/instr.cpp.i

src/core/instr.s: src/core/instr.cpp.s

.PHONY : src/core/instr.s

# target to generate assembly for a file
src/core/instr.cpp.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/instr.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/instr.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/instr.cpp.s
.PHONY : src/core/instr.cpp.s

src/core/parser.o: src/core/parser.cpp.o

.PHONY : src/core/parser.o

# target to build an object file
src/core/parser.cpp.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/parser.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/parser.cpp.o
.PHONY : src/core/parser.cpp.o

src/core/parser.i: src/core/parser.cpp.i

.PHONY : src/core/parser.i

# target to preprocess a source file
src/core/parser.cpp.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/parser.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/parser.cpp.i
.PHONY : src/core/parser.cpp.i

src/core/parser.s: src/core/parser.cpp.s

.PHONY : src/core/parser.s

# target to generate assembly for a file
src/core/parser.cpp.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/parser.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/parser.cpp.s
.PHONY : src/core/parser.cpp.s

src/core/pass.o: src/core/pass.cpp.o

.PHONY : src/core/pass.o

# target to build an object file
src/core/pass.cpp.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/pass.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/pass.cpp.o
.PHONY : src/core/pass.cpp.o

src/core/pass.i: src/core/pass.cpp.i

.PHONY : src/core/pass.i

# target to preprocess a source file
src/core/pass.cpp.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/pass.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/pass.cpp.i
.PHONY : src/core/pass.cpp.i

src/core/pass.s: src/core/pass.cpp.s

.PHONY : src/core/pass.s

# target to generate assembly for a file
src/core/pass.cpp.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/pass.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/pass.cpp.s
.PHONY : src/core/pass.cpp.s

src/core/value.o: src/core/value.cpp.o

.PHONY : src/core/value.o

# target to build an object file
src/core/value.cpp.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/value.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/value.cpp.o
.PHONY : src/core/value.cpp.o

src/core/value.i: src/core/value.cpp.i

.PHONY : src/core/value.i

# target to preprocess a source file
src/core/value.cpp.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/value.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/value.cpp.i
.PHONY : src/core/value.cpp.i

src/core/value.s: src/core/value.cpp.s

.PHONY : src/core/value.s

# target to generate assembly for a file
src/core/value.cpp.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/core/value.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/core/value.cpp.s
.PHONY : src/core/value.cpp.s

src/geometry/point.o: src/geometry/point.cpp.o

.PHONY : src/geometry/point.o

# target to build an object file
src/geometry/point.cpp.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/point.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/geometry/point.cpp.o
.PHONY : src/geometry/point.cpp.o

src/geometry/point.i: src/geometry/point.cpp.i

.PHONY : src/geometry/point.i

# target to preprocess a source file
src/geometry/point.cpp.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/point.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/geometry/point.cpp.i
.PHONY : src/geometry/point.cpp.i

src/geometry/point.s: src/geometry/point.cpp.s

.PHONY : src/geometry/point.s

# target to generate assembly for a file
src/geometry/point.cpp.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/geometry/point.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/geometry/point.cpp.s
.PHONY : src/geometry/point.cpp.s

src/simulators/mill_tool.o: src/simulators/mill_tool.cpp.o

.PHONY : src/simulators/mill_tool.o

# target to build an object file
src/simulators/mill_tool.cpp.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/mill_tool.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/mill_tool.cpp.o
.PHONY : src/simulators/mill_tool.cpp.o

src/simulators/mill_tool.i: src/simulators/mill_tool.cpp.i

.PHONY : src/simulators/mill_tool.i

# target to preprocess a source file
src/simulators/mill_tool.cpp.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/mill_tool.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/mill_tool.cpp.i
.PHONY : src/simulators/mill_tool.cpp.i

src/simulators/mill_tool.s: src/simulators/mill_tool.cpp.s

.PHONY : src/simulators/mill_tool.s

# target to generate assembly for a file
src/simulators/mill_tool.cpp.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/mill_tool.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/mill_tool.cpp.s
.PHONY : src/simulators/mill_tool.cpp.s

src/simulators/sim_mill.o: src/simulators/sim_mill.cpp.o

.PHONY : src/simulators/sim_mill.o

# target to build an object file
src/simulators/sim_mill.cpp.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/sim_mill.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/sim_mill.cpp.o
.PHONY : src/simulators/sim_mill.cpp.o

src/simulators/sim_mill.i: src/simulators/sim_mill.cpp.i

.PHONY : src/simulators/sim_mill.i

# target to preprocess a source file
src/simulators/sim_mill.cpp.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/sim_mill.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/sim_mill.cpp.i
.PHONY : src/simulators/sim_mill.cpp.i

src/simulators/sim_mill.s: src/simulators/sim_mill.cpp.s

.PHONY : src/simulators/sim_mill.s

# target to generate assembly for a file
src/simulators/sim_mill.cpp.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/simulators/sim_mill.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/simulators/sim_mill.cpp.s
.PHONY : src/simulators/sim_mill.cpp.s

src/synthesis/output.o: src/synthesis/output.cpp.o

.PHONY : src/synthesis/output.o

# target to build an object file
src/synthesis/output.cpp.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/output.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/synthesis/output.cpp.o
.PHONY : src/synthesis/output.cpp.o

src/synthesis/output.i: src/synthesis/output.cpp.i

.PHONY : src/synthesis/output.i

# target to preprocess a source file
src/synthesis/output.cpp.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/output.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/synthesis/output.cpp.i
.PHONY : src/synthesis/output.cpp.i

src/synthesis/output.s: src/synthesis/output.cpp.s

.PHONY : src/synthesis/output.s

# target to generate assembly for a file
src/synthesis/output.cpp.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/synthesis/output.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/synthesis/output.cpp.s
.PHONY : src/synthesis/output.cpp.s

src/system/bmp_output.o: src/system/bmp_output.cpp.o

.PHONY : src/system/bmp_output.o

# target to build an object file
src/system/bmp_output.cpp.o:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/bmp_output.cpp.o
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/system/bmp_output.cpp.o
.PHONY : src/system/bmp_output.cpp.o

src/system/bmp_output.i: src/system/bmp_output.cpp.i

.PHONY : src/system/bmp_output.i

# target to preprocess a source file
src/system/bmp_output.cpp.i:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/bmp_output.cpp.i
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/system/bmp_output.cpp.i
.PHONY : src/system/bmp_output.cpp.i

src/system/bmp_output.s: src/system/bmp_output.cpp.s

.PHONY : src/system/bmp_output.s

# target to generate assembly for a file
src/system/bmp_output.cpp.s:
	$(MAKE) -f CMakeFiles/TriangulateTerrainMap.dir/build.make CMakeFiles/TriangulateTerrainMap.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/src/system/bmp_output.cpp.s
	$(MAKE) -f CMakeFiles/bmp-prog.dir/build.make CMakeFiles/bmp-prog.dir/src/system/bmp_output.cpp.s
.PHONY : src/system/bmp_output.cpp.s

test/checker_tests.o: test/checker_tests.cpp.o

.PHONY : test/checker_tests.o

# target to build an object file
test/checker_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/checker_tests.cpp.o
.PHONY : test/checker_tests.cpp.o

test/checker_tests.i: test/checker_tests.cpp.i

.PHONY : test/checker_tests.i

# target to preprocess a source file
test/checker_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/checker_tests.cpp.i
.PHONY : test/checker_tests.cpp.i

test/checker_tests.s: test/checker_tests.cpp.s

.PHONY : test/checker_tests.s

# target to generate assembly for a file
test/checker_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/checker_tests.cpp.s
.PHONY : test/checker_tests.cpp.s

test/cut_tests.o: test/cut_tests.cpp.o

.PHONY : test/cut_tests.o

# target to build an object file
test/cut_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_tests.cpp.o
.PHONY : test/cut_tests.cpp.o

test/cut_tests.i: test/cut_tests.cpp.i

.PHONY : test/cut_tests.i

# target to preprocess a source file
test/cut_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_tests.cpp.i
.PHONY : test/cut_tests.cpp.i

test/cut_tests.s: test/cut_tests.cpp.s

.PHONY : test/cut_tests.s

# target to generate assembly for a file
test/cut_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/cut_tests.cpp.s
.PHONY : test/cut_tests.cpp.s

test/line_tests.o: test/line_tests.cpp.o

.PHONY : test/line_tests.o

# target to build an object file
test/line_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/line_tests.cpp.o
.PHONY : test/line_tests.cpp.o

test/line_tests.i: test/line_tests.cpp.i

.PHONY : test/line_tests.i

# target to preprocess a source file
test/line_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/line_tests.cpp.i
.PHONY : test/line_tests.cpp.i

test/line_tests.s: test/line_tests.cpp.s

.PHONY : test/line_tests.s

# target to generate assembly for a file
test/line_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/line_tests.cpp.s
.PHONY : test/line_tests.cpp.s

test/mill_simulator_tests.o: test/mill_simulator_tests.cpp.o

.PHONY : test/mill_simulator_tests.o

# target to build an object file
test/mill_simulator_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/mill_simulator_tests.cpp.o
.PHONY : test/mill_simulator_tests.cpp.o

test/mill_simulator_tests.i: test/mill_simulator_tests.cpp.i

.PHONY : test/mill_simulator_tests.i

# target to preprocess a source file
test/mill_simulator_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/mill_simulator_tests.cpp.i
.PHONY : test/mill_simulator_tests.cpp.i

test/mill_simulator_tests.s: test/mill_simulator_tests.cpp.s

.PHONY : test/mill_simulator_tests.s

# target to generate assembly for a file
test/mill_simulator_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/mill_simulator_tests.cpp.s
.PHONY : test/mill_simulator_tests.cpp.s

test/parse_tests.o: test/parse_tests.cpp.o

.PHONY : test/parse_tests.o

# target to build an object file
test/parse_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/parse_tests.cpp.o
.PHONY : test/parse_tests.cpp.o

test/parse_tests.i: test/parse_tests.cpp.i

.PHONY : test/parse_tests.i

# target to preprocess a source file
test/parse_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/parse_tests.cpp.i
.PHONY : test/parse_tests.cpp.i

test/parse_tests.s: test/parse_tests.cpp.s

.PHONY : test/parse_tests.s

# target to generate assembly for a file
test/parse_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/parse_tests.cpp.s
.PHONY : test/parse_tests.cpp.s

test/point_tests.o: test/point_tests.cpp.o

.PHONY : test/point_tests.o

# target to build an object file
test/point_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/point_tests.cpp.o
.PHONY : test/point_tests.cpp.o

test/point_tests.i: test/point_tests.cpp.i

.PHONY : test/point_tests.i

# target to preprocess a source file
test/point_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/point_tests.cpp.i
.PHONY : test/point_tests.cpp.i

test/point_tests.s: test/point_tests.cpp.s

.PHONY : test/point_tests.s

# target to generate assembly for a file
test/point_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/point_tests.cpp.s
.PHONY : test/point_tests.cpp.s

test/transformer_tests.o: test/transformer_tests.cpp.o

.PHONY : test/transformer_tests.o

# target to build an object file
test/transformer_tests.cpp.o:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/transformer_tests.cpp.o
.PHONY : test/transformer_tests.cpp.o

test/transformer_tests.i: test/transformer_tests.cpp.i

.PHONY : test/transformer_tests.i

# target to preprocess a source file
test/transformer_tests.cpp.i:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/transformer_tests.cpp.i
.PHONY : test/transformer_tests.cpp.i

test/transformer_tests.s: test/transformer_tests.cpp.s

.PHONY : test/transformer_tests.s

# target to generate assembly for a file
test/transformer_tests.cpp.s:
	$(MAKE) -f CMakeFiles/all-tests.dir/build.make CMakeFiles/all-tests.dir/test/transformer_tests.cpp.s
.PHONY : test/transformer_tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TriangulateTerrainMap"
	@echo "... bmp-prog"
	@echo "... all-tests"
	@echo "... examples/TriangulateTerrainMap.o"
	@echo "... examples/TriangulateTerrainMap.i"
	@echo "... examples/TriangulateTerrainMap.s"
	@echo "... examples/bmp_prog.o"
	@echo "... examples/bmp_prog.i"
	@echo "... examples/bmp_prog.s"
	@echo "... src/core/gprog.o"
	@echo "... src/core/gprog.i"
	@echo "... src/core/gprog.s"
	@echo "... src/core/instr.o"
	@echo "... src/core/instr.i"
	@echo "... src/core/instr.s"
	@echo "... src/core/parser.o"
	@echo "... src/core/parser.i"
	@echo "... src/core/parser.s"
	@echo "... src/core/pass.o"
	@echo "... src/core/pass.i"
	@echo "... src/core/pass.s"
	@echo "... src/core/value.o"
	@echo "... src/core/value.i"
	@echo "... src/core/value.s"
	@echo "... src/geometry/point.o"
	@echo "... src/geometry/point.i"
	@echo "... src/geometry/point.s"
	@echo "... src/simulators/mill_tool.o"
	@echo "... src/simulators/mill_tool.i"
	@echo "... src/simulators/mill_tool.s"
	@echo "... src/simulators/sim_mill.o"
	@echo "... src/simulators/sim_mill.i"
	@echo "... src/simulators/sim_mill.s"
	@echo "... src/synthesis/output.o"
	@echo "... src/synthesis/output.i"
	@echo "... src/synthesis/output.s"
	@echo "... src/system/bmp_output.o"
	@echo "... src/system/bmp_output.i"
	@echo "... src/system/bmp_output.s"
	@echo "... test/checker_tests.o"
	@echo "... test/checker_tests.i"
	@echo "... test/checker_tests.s"
	@echo "... test/cut_tests.o"
	@echo "... test/cut_tests.i"
	@echo "... test/cut_tests.s"
	@echo "... test/line_tests.o"
	@echo "... test/line_tests.i"
	@echo "... test/line_tests.s"
	@echo "... test/mill_simulator_tests.o"
	@echo "... test/mill_simulator_tests.i"
	@echo "... test/mill_simulator_tests.s"
	@echo "... test/parse_tests.o"
	@echo "... test/parse_tests.i"
	@echo "... test/parse_tests.s"
	@echo "... test/point_tests.o"
	@echo "... test/point_tests.i"
	@echo "... test/point_tests.s"
	@echo "... test/transformer_tests.o"
	@echo "... test/transformer_tests.i"
	@echo "... test/transformer_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

