#ifndef GCA_STATE_NAMES_H
#define GCA_STATE_NAMES_H

#define GCA_POSITION_STATE 2
#define GCA_ORIENTATION_CHECKER_STATE 3
#define GCA_ORIENTATION_STATE 200
#define GCA_MOVE_CHECKER_STATE 201
#define GCA_ABS_TO_REL_STATE 2003
#define GCA_REL_TO_ABS_STATE 2004
#define GCA_G0_FILTER_STATE 2002
#define GCA_BOUNDS_CHECKER_STATE 2000
#define GCA_SIM_MILL_STATE 2005

#endif
